### ISSUE TITLE
Stuck on: "Starting deployment"

### ISSUE THREAD

**Issue by ziat007** [Nexus-Mods/Vortex#4430] opened 2019-05-09 12:07 UTC
**Describe the bug**
When managing any game (Stardew, KCD, Subnautica) the manager gets stuck on "Starting deployment"

I have attempted reinstalling different version of Vortex (latest and older).

**To Reproduce**
Attempt to mod manage any game in my library.

**Expected behavior**
The mod manager installs necessary files and lets me easily install mods

**Screenshots**
https://imgur.com/NjBS4Va

**Platform (please complete the following information):**
Vortex 4/8/2019
Windows 10 1809 x64

**Additional context**
https://pastebin.com/7BiUiAUY

**Comment by TanninOne** [comment] 2019-05-09 13:24
duplicate of #4404

**Closed by TanninOne** 2019-05-09 13:24 UTC
