### ISSUE TITLE
Vortex Update

### ISSUE THREAD

**Issue by frustrated42** [Nexus-Mods/Vortex#12775] opened 2022-08-17 10:43 UTC
**Describe the bug**

**To Reproduce**
1. Go to '...' vortex
2. Click on '....' deploy mods
3. Scroll down to '....' Holiday Spirits or Sanctuary Root Cellar
4. See error CDT

**Expected behavior**
A clear and concise description of what you expected to happen. CDT

**Screenshots**
If applicable, add screenshots to help explain your problem. No Screen shot available 

**Platform (please complete the following information):**
 - OS: [e.g. Windows 10] Windows 11 Pro
 - Vortex Version [e.g. 0.16.12] 1.6.7

**Additional context**
Yesterday when vortex updated, I was playing Fallout 4 and vortex shut me down and updated told me I had to update .NET 6.6 and now my game CDT'S at will. I used L.O.O.T it told me everything was fine cleaned up a few plugins worked for 10 min and same issue.  I took out the save files and refreshed to a new game same issue. My roomate plays Fallout 4 and Witcher 3  and his version updated as well but vortex could not reconize that it managed both games. He took both out and re installed and now his games CDT'S at will as well. I currently updated my mods that had a few updates no issues until vortex update. Steam Everything is Updated to current . I tried Need For Speed Payback and it plays the game just fine with no Issues. So vortex is affecting Fallout 4 and Witcher 3
[DxDiag.txt](https://github.com/Nexus-Mods/Vortex/files/9358736/DxDiag.txt) I'm going to try Resident Evil 2&3 to see if any issue arises with them. I don't know if it was a bad download as it has happened before but I'm going to try and see if those are the only two.

**Comment by TanninOne** [comment] 2022-08-17 13:33
duplicate of #3300

**Closed by TanninOne** 2022-08-17 13:33 UTC
