### ISSUE TITLE
[UX] User Feedback when Launching Game

### ISSUE THREAD

**Issue by Foxtrek64** [Nexus-Mods/Vortex#2165] opened 2018-11-14 00:08 UTC
**Is your feature request related to a problem? Please describe.**
When launching a game, the "play" button will turn a darker shade, though there is not a large amount of positive feedback that shows the game has been launched successfully. This lack of feedback may cause users to believe that the game has not launched, causing them to click the play button again, and resulting in [multiple instances of the game being launched](https://github.com/Nexus-Mods/Vortex/issues/2123). With resource-intensive games like Fallout 4, this can bring weaker systems to their knees.

**Describe the solution you'd like**
We can go multiple ways with this, though I propose we follow Steam's methodology by showing a themed modal that closes automatically. A cancel button, optionally, may be beneficial.

**Describe alternatives you've considered**
#1216 brings up a good idea. This would also succeed in providing that positive user feedback, though I feel this has the possibility of causing the user to believe (erroneously) that the game did not launch and Vortex crashed. While I do believe this is a valid suggestion, I don't believe it's entirely appropriate for this particular issue. That said, should the user want Vortex to close or minimize on game launch, then I believe that should be a configurable option (though that's discussion for that issue).

**Additional context**
When I first downloaded Vortex, this was an issue I experienced two or three times before I learned to look for the play button changing colors (it staying "pressed" is a UI bug in itself, but it's a bug that provides the user with a small amount of feedback where there otherwise would be none). I don't believe good UX design should have users looking for clues that their input was received. Steam's solution is elegant and descriptive, providing information specifying the game and the fact that it is starting. This gives the user immediate, easy to understand feedback.

**Comment by TanninOne** [comment] 2018-11-14 09:36
duplicate of #1221

**Closed by TanninOne** 2018-11-14 09:36 UTC
Labels: enhancement
