### ISSUE TITLE
Mods installation not ending

### ISSUE THREAD

**Issue by Technomancer9934** [Nexus-Mods/Vortex#6539] opened 2020-06-14 23:10 UTC
I use Vortex 1.2.16 and windows 10.
I've followed the tutorial about installing mods but when I try to install a mod (for Fallout New Vegas), no matter if it's from a file or from download via vortex, the mod never install. It stay in "Installing" state and I can't do anything, even removing it.
At the time I wrote this, it's been in this state for about 40 minutes for a installation by file.
Before this one, I tried with a mod download via vortex for the same result. I tried to restart vortex then my PC but there was no effect on the problem.
![image](https://user-images.githubusercontent.com/25689906/84606185-fc0f8800-aea3-11ea-9d24-267153eb083a.png)

**Comment by IDCs** [comment] 2020-06-16 08:09
Hi @Technomancer9934, can you please send us your vortex.log files which can be found inside your %appdata%/vortex directory

**Comment by Technomancer9934** [comment] 2020-06-16 20:47
[vortex.log](https://github.com/Nexus-Mods/Vortex/files/4789030/vortex.log)

**Comment by TanninOne** [comment] 2021-03-18 08:53
Does this still happen in 1.4?

**Comment by IDCs** [comment] 2021-04-07 06:54
Hey @Technomancer9934 - sorry it took us so long to get back to you on this one - can you please confirm whether Vortex 1.4.9 fixes this problem. The installation process has seen quite a few modifications since 1.2.16 and it's highly likely that this has been fixed.

**Comment by Technomancer9934** [comment] 2021-04-07 11:15
I forgot I had this problem. Not that long after this I changed my PC and reinstalled Vortex on the new one. Since then, I had no new problem. (but it's been some times since last time I updated it and used it).

**Comment by IDCs** [comment] 2021-04-07 12:42
Fair enough - in that case I hope you don't mind if I close this issue for now under the assumption that it has been fixed. Please feel free to re-open if you ever find yourself using Vortex again and encounter it yet again.

One thing I'd like to mention though - we've been informed by some users that the perpetual installation "bug" is usually caused by their Anti Virus software blocking our mod installer from completing its operations. So if you _do_ encounter this issue again - please try to temporarily disable your AV while you're modding your game using Vortex.

We know for a fact that "Comodo AntiVirus" will cause this issue.

**Closed by IDCs** 2021-04-07 12:42 UTC
Labels: waiting for reply
