### ISSUE TITLE
Feature: Compact Mode

### ISSUE THREAD

**Issue by ArtaiosGreybark** [Nexus-Mods/Vortex#1048] opened 2018-09-19 23:33 UTC
The space of the plugin and mod lines is very generous right now. So much so that it feels off. You could fit 4 lines in 2. A compact mod that condenses everything so you can see more mods at once would be very nice.

**Comment by TanninOne** [comment] 2018-09-20 06:51
Duplicate of #87

**Closed by TanninOne** 2018-09-20 06:51 UTC
