### ISSUE TITLE
SKSE64(steamVSvortex)

### ISSUE THREAD

**Issue by AlinaMarev** [Nexus-Mods/Vortex#7359] opened 2020-09-09 08:13 UTC
I cannot open SKSE64 through vortex. looked on the nexus forums, seems to be something with the update. i'm sure you're already working on that, regardless, as a result I have to open it via steam. the problem is that the steam version doesn't have any of my vortex mods installed.

**Comment by IDCs** [comment] 2020-09-09 09:25
Hi @AlinaMarev, we are unaware of any issues with running SKSE64 through Vortex - I just started it on my end without an issue.

Can you please give us more information as to what error you're actually getting ? If it's simply the game crashing immediately on start-up, that's not tied to Vortex's interaction with SKSE - that's an issue caused by your mods.

**Comment by AlinaMarev** [comment] 2020-09-09 09:37
SKSE64 works fine with skyrim, but not with special addition? maybe i'm missing something super simple.

**Comment by IDCs** [comment] 2020-09-09 09:52
Hey @AlinaMarev, SKSE64 is meant to only work with SSE - regular Skyrim uses a different SKSE build.

Can you please confirm how you installed the script extender in the first place ? did you install SKSE64 through one of Vortex's notifications ?

If you installed it manually, please have a read through our wiki page explaining how to set up script extenders to work in Vortex https://wiki.nexusmods.com/index.php/Tool_Setup:_Script_Extenders

**Comment by AlinaMarev** [comment] 2020-09-10 02:18
I'll take a look. I think i may end up just uninstalling and re-installing
everything.


Semper Gumbi. Always Flexible.-
Make a plan. Then make a backup plan because the first one won't work. And
when that plan fails too? Semper Gumbi. Adapt and over come.

-ΥΣΜΧ-

-Semper Fi. Always Faithful-

-In Candor Decus-

-

**Comment by IDCs** [comment] 2020-09-10 10:05
I would suggest against burning the house down just because the toaster stopped working - but it's up to you. Going to close the issue as I'm quite certain your issue is down to some configuration error which you should be able to resolve using the wiki article I've linked above.

**Closed by IDCs** 2020-09-10 10:05 UTC
Labels: waiting for reply
