### ISSUE TITLE
Vortex 1.0.3 not detecting mod update of installed mod

### ISSUE THREAD

**Issue by woutercools** [Nexus-Mods/Vortex#5501] opened 2019-09-23 21:03 UTC
I'm sure some installed mod (Sim Settlement - Fallout 4) has an update, but Vortex isn't indicating it has one. The current version is 4.1.4

![image](https://user-images.githubusercontent.com/16439116/65462415-11481080-de56-11e9-9a4e-8cca0aecda5e.png)

Is this a known issue and is there a known solution?

Thanks,
w.

**Comment by TanninOne** [comment] 2019-11-29 14:52
Is this still current? The update from Sim Settlers 4.1.1 is discovered correctly for me.

**Comment by woutercools** [comment] 2019-12-01 13:53
No not any more. For Sim Settlements that is. Once I've removed the version that wouldn't update and installed the current versie, it's discovering the updates again.

But I'm sure about other mods. Sometimes I come across a mods that was updated on the Nexus website, but Vortex wasn't showing it. You can never be 100% sure you're running the latest version of your installed mods.

I love Vortex, but it should have a more solid version tracker. At the moment modders can wildly choose their version naming system. There should be a mandatory version system (like X.Y.Z) so Vortex can easily identify newer version.

**Comment by TanninOne** [comment] 2019-12-02 13:28
Thank you for the feedback.

I agree with the mandatory version system but
a) this isn't a Vortex problem, it would have to be fixed on the website
b) it wouldn't help with the tens of thousands of mods that are already there where the author is no longer active in the community to update the version number.
c) It wouldn't actually solve this problem. If you have "A Quality World Map - Classic with all roads v8.3" installed you don't want it to be updated to "A Quality World Map - Paper v9.0".
The problem is that Nexus doesn't just allow arbitrary version numbers, it also allows variants of the same mod to be uploaded to the same mod page with arbitrary file names.

Vortex does the best we can given incomplete information, the alternative to missing updates is risking false positives.
The first might make you miss an update to a mod that you're already using so presumably it's working. The other might brake your game by replacing a working mod with an incompatible variant.

**Closed by TanninOne** 2019-12-02 13:28 UTC
Labels: bug, waiting for reply
