### ISSUE TITLE
Removing One of Two Profiles Destroys Both

### ISSUE THREAD

**Issue by HumanJHawkins** [Nexus-Mods/Vortex#6018] opened 2020-03-14 08:01 UTC
**Describe the bug**
Removing an obsolete Default profile destroys other non-obsolete profile.

**To Reproduce**
1. Download and configure a bunch of mods under the default profile for Skyrim SE..
2. Duplicate the default profile and begin working from the duplicate.
3. Decide that the duplicate is better and the only one needed, so delete the obsolete default profile.
RESULT: The profile UX disappears and Vortex loses the recognition that it was ever working with Skyrim.
4. Quit and relaunch.
5. Configure Vortex to once again manage Skyrim SE.
RESULT: It looks like your profile survived, but it didn't... At best, it is the original default you copied from. But it also seems to corrupt FNIS. Unsure of the extent of the damage, but it is bad.

**Expected behavior**
Expected my active profile to remain. Expected that if there was some reason I should not delete the original default profile, that the software would not have offered to do so.

**Platform (please complete the following information):**
 - OS: Windows 10
 - Vortex Version: 1.1.14

**Comment by IDCs** [comment] 2020-03-16 08:28
Hi @HumanJHawkins,

Unfortunately we are unable to reproduce this. The fact that you were kicked out of actively managing SSE suggests that the currently _active_ profile had been removed (be it the newly created profile or the obsolete one) and the other non-active profile had remained behind. FNIS issues would indeed be reported in this scenario.

Are you able to reproduce this reliably ? if so, can you please send us a short video/gif showcasing the behaviour and also attach your vortex.log and state information using Vortex's feedback system?

**Comment by TanninOne** [comment] 2020-03-16 10:00
To clarify: If you have Vortex run FNIS automatically, it will generate separte FNIS data files for each profile and thus they may be outdated (using the fnis data from the old profile) until you deployed again.

**Comment by HumanJHawkins** [comment] 2020-03-17 02:05
It is possible that the default was active when I deleted it... I wouldn't think so given what I was doing, but I might have activated it to switch back, then realized I should delete it to work from a copy of the other for example. I just can't remember.

Unfortunately I am not in a position to work toward reproducing it at this time... Loads of time into changes and rebuilding now that I don't want to put at risk. So this might need to go to the bug graveyard (or whatever you do with non-reproducible issues).

Regarding deleting the active profile, if that is possible and causes problems it would make sense to check for and prevent that before proceeding. Sorry I can't be more help by testing that now.

Thanks!

**Comment by IDCs** [comment] 2020-03-17 07:06
Thanks for getting back to us @HumanJHawkins, we have changed the remove profile dialog message to inform users when/if they're attempting to delete the active profile - this will hopefully prevent users from removing it by mistake.

Given that we're unable to reproduce this ourselves, I'm going to close this issue but will keep an eye out for this use case. As a final step, could you please send us your vortex.log files and state information through Vortex's feedback system ? Just in case there's something in there that might clarify what happened.

**Closed by IDCs** 2020-03-17 07:06 UTC
Labels: cant reproduce, waiting for reply

**Comment by HumanJHawkins** [comment] 2020-03-17 18:22
Logs are sent... Unfortunately they may be useless... Couldn't find any as old as the issue. Thanks though.
