### ISSUE TITLE
Vortex failing to update the masterlist in Skyrim 

### ISSUE THREAD

**Issue by LORDoritos42** [Nexus-Mods/Vortex#6256] opened 2020-05-18 02:10 UTC
-This error occurs both in the Skyrim Legendary Edition and in the Skyrim Special Edition. When I click the "reset masterlist" button in the plugins tab on Vortex I get three error notifications here there are in order:

*Message 1:
-Failed to update masterlist (they tell me to go into the appdata folder to delete the masterlist folder to force vortex to download a new one but this does not resolve the issue"

*Into details: 
-LOOT operation "updateMasterlist" failed: Git operation failed. Details: -4; remote 'origin' already exists: libgit2 error

*Message2: Vortex tried to acess "C:\Users\arild\AppData\Roaming\Vortex\skyrimse\masterlist\masterlist.yaml" but it doesn´t exist.
cause.errno:-4058
cause.code: ENOENT
cause.syscall: stat
cause.path: C:\Users\arild\AppData\Roaming\Vortex\skyrimse\masterlist\masterlist.yaml
code:  ENOENT
path:  C:\Users\arild\AppData\Roaming\Vortex\skyrimse\masterlist\masterlist.yaml

*Into details:
"ENOENT: no such file or directory, stat 'C:\Users\arild\AppData\Roaming\Vortex\skyrimse\masterlist\masterlist.yaml'
Error
    at Object.statAsync (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:141:27)
    at t.default.<anonymous> (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar.unpacked\bundledPlugins\gamebryo-plugin-management\index.js:42:19009)
    at Generator.next (<anonymous>)
    at a (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar.unpacked\bundledPlugins\gamebryo-plugin-management\index.js:42:12516)"

*Message 3:
Failed to reset masterlist
LOOT operation "update masterlist" failed: Git operation failed. Details: -4; remote 'origin' already exists: libgit 2 error

cause.func: updateMasterlist
func:  updateMasterlist

*into Details:
"Error: LOOT operation "updateMasterlist" failed: Git operation failed. Details: -4; remote 'origin' already exists: libgit2 error
    at handleResponse (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar.unpacked\bundledPlugins\gamebryo-plugin-management\index.js:42:32655)
    at Socket.<anonymous> (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar.unpacked\bundledPlugins\gamebryo-plugin-management\index.js:42:31292)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:308:12)
    at readableAddChunk (_stream_readable.js:289:11)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:182:23)"

**Expected behavior**

**Screenshots**
-Some prints showing ther error messages:
-https://user-images.githubusercontent.com/65519278/82167557-97f0a880-9892-11ea-95a7-160949c32cb9.png   ;
-https://user-images.githubusercontent.com/65519278/82167646-dab28080-9892-11ea-801a-1a5f067c1b56.png   ;
-https://user-images.githubusercontent.com/65519278/82167685-f4ec5e80-9892-11ea-8797-083d9dc0cf71.png    ;
-https://user-images.githubusercontent.com/65519278/82167707-033a7a80-9893-11ea-902b-b35a5c1df9a8.png

**Platform:
 - OS: win x64 (10.0.17763)
 - Vortex Version: 1.2.11

**Additional context**
-Since the day these error messages appeared, I uninstalled and reinstalled Vortex a few times (deleting all the remaining folders), uninstalled and reinstalled Skyrim, and uninstalled LOOt. Still the error continues ...

**Comment by LORDoritos42** [comment] 2020-05-18 02:18
-I forgot to post the vortex log. Here it is:

**Comment by TanninOne** [comment] 2020-05-18 11:35
The masterlist is updated by LOOT itself, there isn't really anything I can do or say if it fails. Usually these things are caused by either temporary network problems (your network or the github servers having trouble) or permission issues on the masterlist folder (you can see the path in one of the error messages)

If this problem didn't go away since you posted, try closing vortex, delete "C:\Users\arild\AppData\Roaming\Vortex\skyrimse\masterlist" from windows explorer and try again.

If that still doesn't help the only remaining explanation is that something on your system locally breaks the git update, either weird firewall settings or outdated/broken system dlls (particularly those related to networking/ssl)

**Closed by TanninOne** 2020-05-18 11:35 UTC

**Comment by LORDoritos42** [comment] 2020-06-07 18:15
Hey, I finally managed to solve it. I deleted the "git.config" file that was located directly in my User folder. Now he can download normally in the masterlist folder on vortex. Anyway,thanks for the help

**Comment by TanninOne** [comment] 2020-06-29 08:39
good catch @LORDoritos42 , this may be useful to others with that problem as well.

**Comment by H1ghgrade** [comment] 2022-11-30 04:11
> Hey, I finally managed to solve it. I deleted the "git.config" file that was located directly in my User folder. Now he can download normally in the masterlist folder on vortex. Anyway,thanks for the help

Where is "git.config" located ? I'm using Windows 11 please reply, I have the same problem

**Comment by lordvlads77** [comment] 2023-11-08 21:41
But What really worked for me is actually going to the Firewall settings and allow Vortex trough the firewall though.

**Comment by sanylove00** [comment] 2023-11-19 18:44
If none of the above methods can solve the problem, you can try going to the [loot](https://loot.github.io/docs/help/LOOT-FAQs.html) website and following the instructions.

**Comment by stricq** [comment] 2025-04-24 23:57
I'm having this problem as well and so far, nothing has worked.  How do I allow it through the firewall?  It seems to be using the internet just fine.  Why would only this one thing not work?

**Comment by lordvlads77** [comment] 2025-04-28 04:30
Not sure why that thing wouldn't work for that, It's so long that I had completely forgotten about this comment hehe, I'm on a pretty tight schedule right now, but tomorrow morning I can make myself a break to help you with the steps to allow an application through the firewall, Have a good night ;D.
