### ISSUE TITLE
Sample extension doesn't seem to work

### ISSUE THREAD

**Issue by mihaifm** [Nexus-Mods/Vortex#9624] opened 2021-07-11 23:17 UTC
Hi

I followed these steps to build the sample extension:

    git clone https://github.com/Nexus-Mods/Vortex
    cd Vortex\samples\sample-extension
    yarn install
    yarn build

I copied everything in `dist` to `C:\Users\user\AppData\Roaming\Vortex\plugins\Sample`

The extension fails to load with the following error:

    Failed to load: ext.initFunc(...) is not a function

**Comment by TanninOne** [comment] 2021-07-12 07:28
Can confirm. The problem is caused by webpack 5. I've recently stumbled over this in other projects as well, as webpack 5, using default config we used for wp4, generates invalid exports.
I know how to work around that but I haven't figured out yet why webpack is doing that, the export now is just completely silly.

Anyway, for the time being I'd suggest downgrading to webpack 4.

**Comment by mihaifm** [comment] 2021-07-12 17:10
Downgrading webpack did the trick, thanks for the workaround.

**Comment by TanninOne** [comment] 2022-02-07 13:25
should be fixed now

**Closed by TanninOne** 2022-02-07 13:25 UTC
