### ISSUE TITLE
(Feature Request) Omod-Ready 7zip support / Oblivion Omod support (As example plugins)

### ISSUE THREAD

**Issue by Ah-Ftagn** [Nexus-Mods/Vortex#1296] opened 2018-10-12 13:53 UTC
When attempting to install omod files from the oblivion nexus, their contents appear to be simply dumped into the oblivion data folder. 

Installation scripts and conversion data are ignored and installed alongside all other files and folders in the Data folder, leaving an ungodly mess in the data folder to comb through and a host of file conflict notifications for files that aren't even used by the game itself (Omod conversion files for example).

Given that Nexus Mods started with Morrowind and Oblivion mods, perhaps the example plugin/plugins  to show off the extension system should be support for OMOD or BAIN files for Oblivion? 

Comment the source code for those reading it as part of the tutorial to program extensions and you've basically added a feature AND given a series of examples on how to extend Vortex Mod Manager.

**Comment by TanninOne** [comment] 2018-10-12 14:30
duplicate of #406

**Closed by TanninOne** 2018-10-12 14:30 UTC
