### ISSUE TITLE
Vortex lost files of reintalled mods then development in run

### ISSUE THREAD

**Issue by hadaev8** [Nexus-Mods/Vortex#13946] opened 2023-02-03 10:31 UTC
**Describe the bug**
After reinstalling mods one after another vortex lost files of second mod.

**To Reproduce**
Reinstall mod A, wait for development start, reinstall mod B

**Expected behavior**
Files are not lost

**Screenshots**

**Platform (please complete the following information):**
 - OS: Windows 10
 - Vortex Version 1.7.4

**Comment by TanninOne** [comment] 2023-02-06 08:09
duplicate of #4637

**Closed by TanninOne** 2023-02-06 08:09 UTC

**Comment by hadaev8** [comment] 2023-02-06 09:25
What information do you need?
