### ISSUE TITLE
Allow batch highlighting

### ISSUE THREAD

**Issue by Patricol** [Nexus-Mods/Vortex#4082] opened 2019-03-29 22:25 UTC
When dealing with a large number of mods, it's rather difficult to use highlighting effectively; there's an enormous time investment involved in highlighting mods.

If the use case is not clearly compelling, I can explain in more detail.

**Comment by TanninOne** [comment] 2020-11-17 12:13
duplicate of #2116

**Closed by TanninOne** 2020-11-17 12:13 UTC
Labels: enhancement
