### ISSUE TITLE
Unable to MOD Fresh install of Fallout 4

### ISSUE THREAD

**Issue by gamerscircle** [Nexus-Mods/Vortex#4325] opened 2019-04-26 11:29 UTC
1.) Uninstalled Vortex - Via the control panel [Vortex-1-0-17-11-1554901229.e]
2.) Uninstalled Fallout 4 - Via Steam
3.) Rebooted
4.) Verified that the Fallout 4 was gone
5.) Installed Fallout ; after install unchecked the "High Resolution Texture Pack"
6.) Installed Vortex; after it installed and ran, I ran into the same issue, but vortex seemed to think it was still managing Fallout 4
7.) I used Revo Unistaller Pro to uninstall Vortex 
8.) Re-installed Vortex and got no errors , accepted that Vortex will handle  NMM links.
9.) Logged onto the NMM website with my default browser.
10.) From the Vortex dashboard, I clicked on the little red head icon [upper right] and was prompted to log in on website. [pressed button], browser tab opened and I pressed the authorize button .
11.) Via Vortex, I clicked on the games tab, there was Zero manged games and [7] Discovered
12.] I hovered my mouse over Fallout 4 and clicked Manage.  Vortex gave me a busy mouse for just a couple of seconds and I have 3 alerts.

   a.) Mods can't be deployed
   b.) Loose files may not get loaded
   c.) failed to sun from profile

13.) For `Mods can't be deployed` I clicked on "Fix" , read the dialog and then clicked on fix that took me to the "mods" tab where I clicked on "suggest"  [the path was updated to the same drive that the game was installed on]  I clicked apply.

I got a dialog stating that the destination folder has to be empty, since I had an previous install of vortex, there was a folder with fallout 4 folder.  I removed the fallout4 folder and the dialog went away.

14.) For ` Loose files may not get loaded` - I clicked on the fix and the prompt went away.
15.) For `failed to sun from profile` - I clicked dismiss
16.) I then went to the NMM site and located a mod to install " Unofficial Fallout 4 Patch " [ 4598 ] and clicked Download: [Vortex] button
17.) The mod downloaded via Vortex, clicked on the install button , then after the install I clicked on the Enable button.

The mouse went into a busy state, followed by a default window sound [the error sound]  and I am unable to use Vortex as it is [Not Responding]
Removed link to state.v2.zip
[vortex.log](https://github.com/Nexus-Mods/Vortex/files/3121097/vortex.log)

**Comment by TanninOne** [comment] 2019-04-26 12:07
There is nothing in your log or state file that would indicate anything going wrong.

Vortex works in two processes (there's actually more but those are part of chrome and we don't do anything with those), the "browser" process and the "renderer". The fact that the entire Window isn't responding indicates that the "browser" process crashed which is really unusual, practically all crash reports we had before affected the renderer process because it's doing 99% of the works.
The browser process does practically nothing except writing application state back to disk and restart the renderer if anything goes wrong with it.

So I'd assume that it was something else, hooked into the process, that caused the crash or some hardware/software defect.
If you restart Vortex, does it start or does it always hang? Could you check in the Windows "Event Viewer" and see if it says anything about Vortex?

Apart from that you may want to update your drivers (graphics card driver in particular) as well as software that has "global" effects on the system, stuff like Antivirus, applications that affect how windows on the screen get layed out, hacks that add transparency to windows beyond what windows supports, stuff like that.

You could also check this thread: https://forums.nexusmods.com/index.php?/topic/7151166-whitescreen-reasons/

Finally: Please, never post your state.v2 directory publicly because it might contain confidential information (e.g. the key that allows you to access nexusmods.com). If you want to send it in, send it to our feedback system where we keep it private.

**Comment by gamerscircle** [comment] 2019-04-26 16:44
When I restart Vortex, it does in fact hang.  I checked through the Event Viewer and I see this:

The application-specific permission settings do not grant Local Activation permission for the COM Server application with CLSID 
{D63B10C5-BB46-4990-A94F-E40B9D520160}
 and APPID 
{9CA88EE3-ACB7-47C8-AFC4-AB702511C276}
 to the user [MYCOMPUTER\MYLOGIN] SID (S-1-5-21-648555347-2402370585-1897957463-1000) from address LocalHost (Using LRPC) running in the application container Unavailable SID (Unavailable). This security permission can be modified using the Component Services administrative tool.

**Comment by gamerscircle** [comment] 2019-04-26 16:45
I have gotten the latest video driver that was just released, I am usually an update behind, just in case.  I will update and report back.

**Comment by gamerscircle** [comment] 2019-04-26 16:46
As for the state.v2 , thank you I will not.  I was following the advise from discord.

**Comment by gamerscircle** [comment] 2019-04-26 17:43
I did a full virus application update and definitions, I also disabled AV and Vortex still hung
I also updated my Nvidia to the latest that didn't work either.

I appreciate your help and sorry about the blow by blow

I am going to visit the link you shared , if you can think of anything else, let me know.

**Comment by gamerscircle** [comment] 2019-04-27 02:06
I think,  this will be my last post on this..  I fixed it?

I went back to a previous version of Vortex , I got a similar error when I went to enable a mod [different one] , but this time the error pointed loadorder.txt and it being "read only"

After I fixed that, the older vortex worked!  I then uninstalled the mod, uninstalled that older Vortex and installed the latest version of Vortex and it didn't hang or white screen.

It is possible that the latest version doesn't do a dialog for the permissions on loadorder.txt like the older version and just hangs?

**Comment by TanninOne** [comment] 2019-04-29 08:16
Which previous version of Vortex did you use for that?

**Comment by gamerscircle** [comment] 2019-04-29 10:15
I downloaded and installed Vortex-1-0-13-1.exe which was the version that when I went to enable a mod gave me a permissions error on loadorder.txt

**Comment by TanninOne** [comment] 2019-04-29 11:19
Ok, thanks, this helps a lot. While I still can't reproduce it, this info reduces the amount of code I'd have to look at from ~100.000 lines to maybe 50. ;)

**Comment by gamerscircle** [comment] 2019-04-29 11:39
I am glad that I can help, I am not to vortex and so far it has been easy to use.  thank you for your support.

**Comment by TanninOne** [comment] 2019-06-17 15:16
I hope this is fixed now but since I was never able to reproduce it I'm afraid I won't know until someone else reports this problem with 0.18.9+ - or not.

**Closed by TanninOne** 2019-06-17 15:16 UTC
Labels: bug
