### ISSUE TITLE
Mods are downloaded to C:/ Drive regardless of settings

### ISSUE THREAD

**Issue by deanrather** [Nexus-Mods/Vortex#138] opened 2018-05-21 07:38 UTC
I've got a smallish SSD for my C:/ drive, and games installed on a larger D:/ drive.
I've configured Vortex correctly, so it's installing and deploying mods to the D:/ drive, but I noticed my HDD fill up.

Sure enough, it looks like the mods are being downloaded to:

`C:\Users\MYNAME\AppData\Roaming\Vortex\skyrimse\downloads`

In this image, you can see my vortex settings, a lot of mods on my C:/ drive, and only a few on D:/.

![snip](https://user-images.githubusercontent.com/164975/40295744-d039067c-5d1d-11e8-9754-a5213f1e5e5a.PNG)

**Comment by TanninOne** [comment] 2018-05-22 06:32
Vortex downloads mods to the directory based on what game they were uploaded to, independent of what game you're currently managing (as long as the download is from nexus), so your mods get dled to the directory configured (or default) for skyrim se.

There is a plan to change this being discussed here: https://forums.nexusmods.com/index.php?/topic/6629301-opinions-please-moddownload-directories/

**Comment by TanninOne** [comment] 2018-08-03 10:00
duplicate of #130

**Closed by TanninOne** 2018-08-03 10:00 UTC
