### ISSUE TITLE
Triaged [Review] - Valheim Extension installing outdated requirements and mods

### ISSUE THREAD

**Issue by Battousai124** [Nexus-Mods/Vortex#14757] opened 2023-10-07 20:24 UTC
Valheim Extension is currently installing outdated requirements and outdated mods.
InSlim - entirely superceeded by bepinex
Bepinex - outdated version
Outdated mods - dont remember the names, they dont exactly break the game, but dont work either

To reproduce, have no management set up, install extension and it will install non useable mods.

**Expected behavior**
For that not to happen. and for the requirement to be always the latest version, instead of a specified one.

**Screenshots**

**Platform (please complete the following information):**
 - OS: Windows 11
 - Vortex Version: any

**Comment by insomnious** [comment] 2023-12-19 13:24
Thank you for your initial report of this issue. Due to the length of time this issue has been open it is unlikely that we will be able to investigate effectively to determine the root cause of the issue. The issue may have also been resolved in a later release of Vortex and/or the game extension being used. 

Please ensure that you update Vortex and the Valheim extension to the latest version and if the issue still persists, please open a new bug report referencing this issue.

**Closed by insomnious** 2023-12-19 13:24 UTC
