### ISSUE TITLE
Trying to Mod Fallout 4

### ISSUE THREAD

**Issue by D1sfunct10n** [Nexus-Mods/Vortex#14620] opened 2023-08-20 18:12 UTC
Opened up Vortex and was immediately hit with "failed to install extension Game: Fallout 4 from Github.com".

Would give instruction to reproduce but literally all I did was open vortex and it gave me the error.

I expected to open vortex and start modding lmao.

This was the code attached.

connect ETIMEDOUT 2606:50c0:8000::154:443
connect ETIMEDOUT 2606:50c0:8000::154:443
Error: connect ETIMEDOUT 2606:50c0:8000::154:443
    at __node_internal_captureLargerStackTrace (node:internal/errors:490:5)
    at __node_internal_exceptionWithHostPort (node:internal/errors:668:12)
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)
Prior Context:
    at Object.withTmpDir (C:\Program Files\Vortex\resources\app.asar\renderer.js:9456:27)
    at C:\Program Files\Vortex\resources\app.asar\renderer.js:2723:180
    at tryCatcher (C:\Program Files\Vortex\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Program Files\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Program Files\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromiseCtx (C:\Program Files\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:641:10)
    at _drainQueueStep (C:\Program Files\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:97:12)
    at _drainQueue (C:\Program Files\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Program Files\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues (C:\Program Files\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:15:14)
Prior Context:
    at Object.withTmpDir (C:\Program Files\Vortex\resources\app.asar\renderer.js:9456:27)
    at C:\Program Files\Vortex\resources\app.asar\renderer.js:2723:180
    at tryCatcher (C:\Program Files\Vortex\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Program Files\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Program Files\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromiseCtx (C:\Program Files\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:641:10)
    at _drainQueueStep (C:\Program Files\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:97:12)
    at _drainQueue (C:\Program Files\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Program Files\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues (C:\Program Files\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:15:14)

 - OS:  Windows 10
 - Vortex Version 1.9.3

**Comment by HawthorneK456** [comment] 2023-10-30 14:43
Hi,

Thank you for your initial report of this issue. Due to the length of time this issue has been open it is unlikely that we will be able to investigate effectively to determine the root cause of the issue. The issue may have also been resolved in a later release of Vortex. 

Please ensure that you update Vortex to the latest version and if the issue still persists, please open a new bug report referencing this issue. 

Please accept our apologies for not being able to provide a more positive update in relation to this issue but please be assured that we are continuing to develop and maintain Vortex whilst we also undertake the creation of the Nexus Mods App as a successor to Vortex in the future.

**Closed by HawthorneK456** 2023-10-30 14:43 UTC
