### ISSUE TITLE
Whitescreen after install

### ISSUE THREAD

**Issue by Nekai** [Nexus-Mods/Vortex#3050] opened 2019-01-30 23:27 UTC
After the fresh install of Vortex, it opened like it should howver it hung directly after opening. I closed it, then tried reopening it. As per [#181](https://github.com/Nexus-Mods/Vortex/issues/181) I moved everything from F:\Vortex\resources\app.asar.unpacked\bundledPlugins into a new folder on my F:\ drive and it opened as expected. However nothing works. 

I have added these back and so far no issues https://i.imgur.com/mAbrwBp.png

**Comment by IDCs** [comment] 2019-01-31 08:00
Hi @Nekai, can you please have a look within your "C:\Users\{YOUR_USERNAME}\AppData\Roaming\vortex\temp\dumps" folder and attach any files you find in there.

Please also attach any vortex.log files you find in "C:\Users\{YOUR_USERNAME}\AppData\Roaming\vortex\"

Finally, please let us know which Windows and Vortex versions you're using.

**Comment by TanninOne** [comment] 2019-02-01 08:10
Also, please continue adding back extensions until the problem starts appearing again, then let us know which one it was.

**Comment by IDCs** [comment] 2019-02-11 12:45
Hi @Nekai, any update on this ?

**Comment by Nekai** [comment] 2019-02-11 13:08
Yeah, I put back around half of the folders and haven't had an issue since.

**Comment by IDCs** [comment] 2019-02-12 07:13
Thanks @Nekai, could you please continue adding back extensions one by one as Tannin suggested ?

This would help us track down the culprit.

**Comment by Mazurcka** [comment] 2019-03-07 23:01
I've been having the same issue, removing the files will let it run, and I have been able to move back all of the files except the ones with the "game" prefix. I can't find any files in the dumps folder, but here are the log files I have






edit: upon just looking at the log files, 1-4 are from 2018 and probably aren't applicable to my current issue

**Comment by Nekai** [comment] 2019-03-08 00:26
@mazurcka I haven't had any issues running without a lot of the files

**Comment by Mazurcka** [comment] 2019-03-08 01:27
unless I'm mistaking, you can't mod anything without the "game" folder for that game, so Vortex is useless without the "game" folder for the game I'm trying to mod

**Comment by TanninOne** [comment] 2019-03-08 14:37
You need the game- extensions for the games you want to use of  course. Does adding _any_ game extension bring back the crashes or is it only a single / a few of them?

**Comment by Mazurcka** [comment] 2019-03-08 14:47
I only tied 6 or 7 before giving up for the day, but the ones I tried would all cause the crashes, I tried them one at a time so it looks like any game folders I put in cause the crashes

**Comment by TanninOne** [comment] 2019-03-11 10:18
The thing that is most likely to cause a whitescreen for that many game extensions is the registry access. Can you think of anything unusual about your windows registry? Like, have you changed any settings/permissions for it?

Could you try enabling one of the following games: Breaking Wheel, both Dark Souls, dragons dogma, Factorio, Grimrock? Even if you don't have them. For these games (and some others) we don't consult the registry so if you suspicion is true, it shouldn't crash with those.

**Comment by Mazurcka** [comment] 2019-03-18 05:08
I tried moving in the Dragons Dogma and Factorio folders, and neither of those did anything, still just getting a white screen

**Comment by TanninOne** [comment] 2019-03-18 15:23
Your statement is a bit confusing "and neither of those did anything, still just getting a white screen"

We don't expect this extensions to _fix_ the white screen. What we're trying to figure out is whether these game extensions alone _cause_ the white screen.
So starting from _no_ game extensions, which according to your older post lets you start Vortex, add one of the games, does it crash then? With only Dragons Dogma or Factorio and no other game- extension?

**Comment by Mazurcka** [comment] 2019-03-19 06:16
If none of the "game-" prefixed folders are in my "bundledPlugins" Vortex will open just fine, if any of the "game-" prefixed folders are in the "bundledPlugins" folder Vortex will not start, I only get a white screen when I try to run Vortex.
I started out try alphabetically from "game-7daystodie" to "game-dragonage2" one at a time before giving up, and then I tried both Factorio and Dragons Dogma and with every one of the "game-" prefixed folders it causes Vortex to white screen on running it

**Comment by snowbroom** [comment] 2019-06-25 21:14
I have similar problem, I install Vortex, any version of vortex do the same thing, It give me just a white screen. When I try to move bundle plugins folder, its working, but when I move it back everything is white screen again.

**Comment by TanninOne** [comment] 2019-06-26 05:57
Could you too please try adding back plugins in smaller sets to figure out which extensions cause the crash? Is it the "game-*" extensions for you too?

The problem I have with the report by @Mazurcka is that I can't think of any explanation for it.
White screens are caused when a native library causes an exception that is not handled. However, we only use a handful of native libraries in total and some extensions like factorio don't use any of them.

The first thing you should try is if you can put back the feedback extension without it crashing.

If you can start with just the feedback extension, do you get any notification on startup that Vortex has crashed, with an option to send in a report? If so, please do that. If not, please send in a feedback anyway and under "Attach Special File" please attach your log files.

**Comment by Artezzaa** [comment] 2019-07-01 09:41
Having the same problem as most other people here, if I move everything out of the bundledPlugins folder Vortex opens normally and certain folders can be added back but if I add game-witcher3 it goes back to white screening. As was suggested above folders like game-dragons-dogma don't cause it to crash in my case, however I am wanting to mod witcher 3 so I could do with a fix for this.

**Comment by TanninOne** [comment] 2019-09-05 12:21
Since my last question hasn't been answered in over two months I'm assuming the problem is fixed or the people experiencing it aren't around any more. If you still have this problem, please create a new issue and provide the information I asked for, I can't investigate further without it.

**Closed by TanninOne** 2019-09-05 12:21 UTC
Labels: bug, waiting for reply
