### ISSUE TITLE
Unresolved conflicts notification showing when conflicts are resolved.

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/Vortex#11165] opened 2022-02-23 19:44 UTC
**Describe the bug**
Although all conflicts are resolved, Vortex is reporting unresolved conflicts. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Have at step with resolved conflicts from 1.4.17 or lower
2. Update to 1.5.4
3. See notification

**Expected behaviour**
When there are no conflicts there should not be a notification.

**Screenshots**
![collections](https://user-images.githubusercontent.com/31670524/155396014-5ba32b91-a220-41b1-bd78-427ad9ccbdbf.gif)

**Platform (please complete the following information):**
 - OS: Windows 10z
 - Vortex Version 1.5.4

**Additional context**
[vortex.log](https://github.com/Nexus-Mods/Vortex/files/8127323/vortex.log)
https://forums.nexusmods.com/index.php?/topic/11119758-154-conflict-resolving-bug/?view=getnewpost

**Comment by kikimusa1** [comment] 2022-02-23 20:21
okay, here r my logs







Do you require some specific additional info or is that it?

**Comment by epinter** [comment] 2022-02-23 23:03
It's happening with me too, after update to 1.5.4. Hundreds of conflicts that are already resolved are shown as resolved but still notified, also lots of previously resolved conflicts was lost, now showing as unresolved.

**Comment by Soupdragon1** [comment] 2022-02-24 00:16
Same here long list of (resolved) conflicts that won't clear.
Windows 10 Pro 20H2
Vortex 1.5.4

**Comment by IDCs** [comment] 2022-02-24 07:11
duplicate of #11152

**Closed by IDCs** 2022-02-24 07:11 UTC
