### ISSUE TITLE
Review: FATE - Cursed King

### ISSUE THREAD

**Issue by LuxenDM** [Nexus-Mods/Vortex#16410] opened 2024-09-12 02:34 UTC
### Nexus Username

LuxenDM

### Extension URL

https://www.nexusmods.com/site/mods/1032

### Game URL

https://www.nexusmods.com/fate

### Existing Extension URL

https://www.nexusmods.com/site/mods/801

### New features

FATE has 4 distinct games in the series, all using nearly similar engines. Mods that support one game almost always are compatible with the others. This duplicate extension is *intended* to allow users who own multiple games to manage the games independently of one another in vortex. If this should be handled in another manner, please let me know. If needed, you can find the [FATE:CK steam page here](https://store.steampowered.com/app/303690/FATE_The_Cursed_King/)

### Information

- [X] I confirm the above is accurate

### Packaging

- [X] This extension is packaged correctly

### Testing

- [X] This game extension has been tested
### Review Tasks

If a task fails, contact the author to request changes before continuing.

- [ ] Double-check for existing extension
- [ ] Is the extension [packaged correctly](https://github.com/Nexus-Mods/Vortex/wiki/How-to-package-a-game-extension)?
- [ ] Does it install into Vortex?
- [ ] Does it correctly discover the game?
- [ ] Does it successfully install a mod?
- [ ] Does it successfully install a collection?
- [ ] Does the game run correctly with the mods installed? ​

When reviewed and passed, please complete the following tasks:

- [ ] Run the GitHub Actions to add to manifest
- [ ] Contact author
- [ ] Ask Community to enable the Vortex button for the game
- [ ] Update the #vortex-announcements channel on Discord

**Comment by IDCs** [comment] 2024-09-19 11:03
Same as #16409

**Comment by IDCs** [comment] 2024-11-25 08:19
closing as duplicate of #16409

**Closed by IDCs** 2024-11-25 08:19 UTC
Labels: extension :gear:
