### ISSUE TITLE
Vortex Not Launching after install

### ISSUE THREAD

**Issue by ninjahejo** [Nexus-Mods/Vortex#14373] opened 2023-05-31 16:09 UTC
I just installed Vortex & it seems not launching. when I check task manager, it just appear for second and gone.

Windows 11 22H2
Not yet install mod

Last log from dump : 
Exception time: 1685548941
Exception code: 80000003
Exception address: 00007FF73245B831
writing dump C:\Users\Administrator\AppData\Roaming\Vortex\temp\dumps\crash-main-1685548941290.dmp
success

**Comment by HawthorneK456** [comment] 2023-10-24 08:59
Hi,

Thank you for your initial report of this issue. Due to the length of time this issue has been open it is unlikely that we will be able to investigate effectively to determine the root cause of the issue. The issue may have also been resolved in a later release of Vortex. 

Please ensure that you update Vortex to the latest version and if the issue still persists, please open a new bug report referencing this issue. 

Please accept our apologies for not being able to provide a more positive update in relation to this issue but please be assured that we are continuing to develop and maintain Vortex whilst we also undertake the creation of the Nexus Mods App as a successor to Vortex in the future.

**Closed by HawthorneK456** 2023-10-24 08:59 UTC
