### ISSUE TITLE
Vortex hangs a long time on "Loading Extensions" screen (WINE)

### ISSUE THREAD

**Issue by XXXBold** [Nexus-Mods/Vortex#9629] opened 2021-07-12 09:14 UTC
**Describe the bug**
When starting Vortex, it takes a very long time for it to pass the "Loading Extensions" screen, it hangs there like 20 minutes or so. In the console output, I can see a repeating message over and over, counting from 1 to (INT_MAX) while the application hangs (see logfiles).

I'm using a new WINE prefix for this test, and only installed dotnet48 before installing Vortex. Therefore, no additional applications or games are installed there.

**To Reproduce**
1. Set environmentvariable for new WINE-Prefix on desired path. e.g. `export WINEPREFIX=/home/user/.winetest`
2. Install .NET runtime 4.8. using winetricks: `winetricks --force dotnet48`
3. Pass through all installers
4. Start vortex setup: `wine "path/to/vortex-setup-1.4.14.exe"`
5. Installations seems to work fine
6. When Vortex starts, the issue will always occur.

**Expected behavior**
The application should not hang that long

**Logfiles**
Log is recorded for a full startup of the application, and close it afterwards.
Terminal output when running `wine Vortex.exe` (shorted): 
[winelog.txt](https://github.com/Nexus-Mods/Vortex/files/6800101/winelog.txt)
vortex.log: 
[vortex.log](https://github.com/Nexus-Mods/Vortex/files/6800104/vortex.log)

**Screenshots**
![vortex-load-extensions](https://user-images.githubusercontent.com/30773753/125253058-87965b00-e2e8-11eb-8237-b8fe32050a8e.png)

**Platform (please complete the following information):**
 - OS: Linux Mint 20.1 (Using WINE 6.12-staging)
 - Vortex Version: 1.14.4

**Additional context**
I'm aware that running Vortex using wine might not be supported. However, I've found that this issue also seems to be present for some users on Windows, so it might be a general bug that should be fixed anyway.
If you need further information let me know, and I'll see what I can do.

**Comment by IDCs** [comment] 2021-07-12 09:37
Hi @XXXBold, you are correct, Vortex is not officially supported on Linux, with or without wine. The log you sent us contains no information that would suggest that this is a multi-platform issue, in fact according to the log file all extensions had been initialized successfully.

As we can't test this on Linux (we simply don't have the resources to do it) we would need someone that is affected by this bug on Windows to report it so we can investigate. You mentioned Windows users _are_ affected by this as well, please ask them to submit a bug report with all file attachments included (we're currently not aware of any issues of this sort on Windows)

I'm sorry to say I'm going to close this as the plan is to one day add native Linux support (TBD) at which point any WINE specific issues will become redundant. Keep an eye out on https://github.com/Nexus-Mods/Vortex/issues/2862

**Comment by IDCs** [comment] 2021-07-12 09:59
Actually - @XXXBold something I just noticed in your log:
```
Mon, 12 Jul 2021 08:41:48 GMT - debug: once extension=symlink_activator_elevate
Mon, 12 Jul 2021 09:06:23 GMT - debug: once extension=updater
```

There seems to be quite a hefty "hang" when the symlink activator extension starts up which would indeed indicate some sort of weirdness due to the WINE environment (or rather the fact that the activators/deployment methods were not developed with Linux in mind).

**Comment by XXXBold** [comment] 2021-07-12 10:45
@IDCs Thanks for your response. 

Would it be possible, as a workaround, to disable the symlink activator extension then, to avoid the hang?

**Comment by IDCs** [comment] 2021-07-12 12:31
Hey @XXXBold - unfortunately the activator extensions are built into the asar archive which means this would require a code change and a new Vortex release. Given that the symlink deployment method is the only activator capable of deploying mods in-between partitions, I don't think allowing users to disable it is wise - especially when 99.99% of our users have no idea what they're doing. I can already imagine the support nightmare of trying to explain to people that they disabled the activator by mistake.

Regardless, you must agree that disabling the extension feels like a band aid fix/hack rather than a proper solution. Try asking for help from the guys on #2862 just in case this is an environment configuration issue.

**Comment by XXXBold** [comment] 2021-07-12 12:50
@IDCs Yes, I agree with you that it doesn't make sense if it would require special handling.

However, I'm not sure if this component is the root of the problem. After Vortex started up, I sometimes get the same hangs, while just selecting options from the GUI, not installing anything, but for example click on settings and on one of the submenus, which makes the whole application pretty unusable.

I think the issue might more likely be UI-related.

**Comment by IDCs** [comment] 2021-07-12 13:15
@XXXBold, I can't rule out the UI. But I think it's more likely to be our winapi native module which is used throughout the application, and _is_ part of the symlink activator "once" function call. That module offers Windows specific functionality and I fear it may act oddly when it's being run through WINE. Again these are all assumptions and guesses as I can't debug this myself.

**Comment by XXXBold** [comment] 2021-07-12 14:21
@IDCs Well, I don't know any win users affected myself, but if you search for "vortex loading extensions" in your preferred search engine, you get some results. Some are considered fixed, or apply to very old versions. 

https://www.reddit.com/r/nexusmods/comments/kz2gu9/vortex_stuck_on_loading_screen_anyone_know_a_fix/
https://www.bountysource.com/issues/93586748-vortex-stuck-at-loading-extensions
https://forums.nexusmods.com/index.php?/topic/9174638-stuck-on-loading-extensions/
https://www.reddit.com/r/FalloutMods/comments/o0s61p/fo4_vortex_stuck_on_loading_extensions/h1x9zkr/

Might do some tests on a VM later, probably I can trigger it there as well.

BTW, could you point me to that native win-module? I might look into it and probably run some debugging, if possible.

**Comment by IDCs** [comment] 2021-07-12 14:55
@XXXBold the repo for the native winapi - https://github.com/Nexus-Mods/node-winapi-bindings

None of those links provide any relevant information I can go by except the bountysource link which links to this issue: https://github.com/Nexus-Mods/Vortex/issues/7670 - it appears to be caused by the old deprecated symlink workaround which indeed would cause errors and long "hangs" as Vortex would attempt to execute a script through a scheduled task; the script had a bug in it which would cause it to never respond to the caller thus hanging indefinitely - that has been fixed in early versions of 1.4.x though so I doubt that's what you're encountering.

**Comment by XXXBold** [comment] 2021-07-16 20:16
I did some tests today, and I was able to figure out which was the last working version without this problem.
Also, the older versions < 1.4.14 most of the time where able to successfully start up (No hang at the "Loading Extensions" Screen), but hang very quick if I click through the UI.

I've created logfiles, for both the last working and the first non-working version, including the vortex.log and the output from wine on the terminal.
Logging is started from installation up to the point where it hangs, or in case of the working version, I've manually quit vortex after clicking through the UI for a while.

Vortex 1.2.10 (most recent which is working):

[winelog-vortex1.2.10.log](https://github.com/Nexus-Mods/Vortex/files/6833112/winelog-vortex1.2.10.log)

Vortex 1.2.11 (oldest which is working):

[winelog-vortex1.2.11.log](https://github.com/Nexus-Mods/Vortex/files/6833161/winelog-vortex1.2.11.log)


Some oi the versions I've tested:
Working: 
1.1.15
1.2.4
1.2.7
1.2.9
1.2.10

Not working (hang when clicking through UI, spamming the message in the terminal as mentioned above):
1.2.13
1.2.11

**Comment by mickname** [comment] 2021-07-23 13:03
For the wine users, the problem is in the `symlink_activator_elevate` code or the winapi bindings. The wine implementation of the `taskschd` is heavily stubbed and returns `E_NOTIMPL`. I guess that isn't handled in the winapi bindings and results in some kind of (near)infinite loop - the wine console is filled with the fixme-level messages. It eventually progresses beyond that, faster if that debug message is disabled. But opening some ui-tabs triggers it again, sometimes (apparently) permanently freezing.

I managed to work around this locally by unpacking the app .asar bundle, replacing these functions using the winapi.GetTasks() function call to return `"an error string"` and `undefined`, respectively:
https://github.com/Nexus-Mods/Vortex/blob/76b77494db78e39568cb12fe31e83c04ce1a2903/src/extensions/symlink_activator_elevate/index.ts#L767
https://github.com/Nexus-Mods/Vortex/blob/76b77494db78e39568cb12fe31e83c04ce1a2903/src/extensions/symlink_activator_elevate/index.ts#L777
And then repacking the bundle again. The program then rightly complains that it is corrupted but that can be ignored.

**Comment by fmagin** [comment] 2022-01-01 12:00
FWIW: If I install Vortex in the Steam Proton Context this issue doesn't appear, with regular wine I run into the same issue.

My (preliminary) setup:
* Elder Scrolls Skyrim via Proton in Steam (with the proton version forced to `Proton-7.0rc2-GE-1`)
* Changed Launch options to your terminal: in my case `kitty; echo %command%`
* Run "Skyrim" via Steam and a terminal opens for me, in which I can easily launch various programs in whatever context Steam sets up (without getting the `Proton: No compat data path?` message)
    * `~/.steam/root/compatibilitytools.d/Proton-7.0rc2-GE-1/proton run skse64_loader.exe`
    * `~/.steam/root/compatibilitytools.d/Proton-7.0rc2-GE-1/proton run Mopy/Wrye Bash.exe`
    * And most importantly: `~/.steam/root/compatibilitytools.d/Proton-7.0rc2-GE-1/proton run ~/Downloads/Vortex\ \(custom\ install\ location\)-1-1-4-16-1633352235.exe`
* with that last command I can then install Vortex into whatever context or wine prefix Steam sets up there
* It is then available with: `~/.steam/root/compatibilitytools.d/Proton-7.0rc2-GE-1/proton run '../../compatdata/489830/pfx/./drive_c/Program Files/Black Tree Gaming Ltd/Vortex/Vortex.exe'`

there are a bunch of issues afterwards, but they seem addressable: 
![image](https://user-images.githubusercontent.com/8415354/147849870-a8462a40-dc9f-4660-97a1-9ec5d58ff8bd.png)

I am not sure what part of this is crucial for this to work (The Glorious eggroll fork? Using it via Steam? Something specific about the Skyrim fixes steam uses for proton?), but I hope this can at least be a start for others.

**Comment by JulianFP** [comment] 2022-01-15 00:00
@fmagin Thank you very much for this, it helped me a lot. I got finally Skyrim SE working with Mods under Linux thanks to your guide. Here is what I did:
- Force the Proton version to the latest gloriouseggroll runner, in my case `Proton-7.0rc3-GE-1`
- Change the launch options to your terminal, in my case `gnome-terminal; echo %command%`
- Click Play and enter following command to install Vortex inside the Proton prefix: `~/.steam/root/compatibilitytools.d/Proton-7.0rc3-GE-1/proton run ~/Downloads/Vortex\ \(custom\ install\ location\)-1-1-4-16-1633352235.exe`
- As soon as Vortex is open, you can close it, and run it from now on with `~/.steam/root/compatibilitytools.d/Proton-7.0rc3-GE-1/proton run '../../compatdata/489830/pfx/./drive_c/Program Files/Black Tree Gaming Ltd/Vortex/Vortex.exe'`
- To fix the 'Mods can't be deployed' error, you have to change the Mods installation directory to 'Z:', which is just your / partition. Just create somewhere in your homefolder an directory for the mods, and enter it in Vortex (you get guided to this by pressing 'Fix' behind the error)
- Install SKSE manually the same way as on Windows (follow the guide in the Readme). You can find your installation directory by going into the steam properites --> Local Files --> Browse.
- Restart Vortex. There should be only two errors left now: '.Net installation broken' and 'Vortex uninstall path doesn't match current executable'. I found out that you can ignore those, installing and running mods works anyway.
- Now download any Mod you want manually from nexusmods.com, go in Vortex into the Mods section, install the mods from File and enable them
- Run the game through Vortex by pressing the Start button behind SKSE in the Dashboard

**Comment by TanninOne** [comment] 2022-01-15 10:28
Didn't come across this earlier. I'm not sure how to fix this as it seems to be tied into wine's implementation of certain functions but if someone can guide me to some docs I'll be happy to add handling for E_NOTIMPL.

To explain the problem: on windows, the implementation of symlinks is a bit borked, users need to provide admin permissions for creating symlinks even if they already have write permissions to the relevant directories. I wouldn't be surprised if this is different within wine because linux should allow symlinks to be created wherever you can create a regular file, why would wine emulate this madness?

Vortex (symlink_acitvator_elevated) has used two different workarounds to get around this problem:
a) (older) start a task with admin rights, then delegate all symlink creation to that task
b) (newer) change group policies to disable this weird behavior system wide

But Vortex also includes a second implementation of symlink deployment altogher (symlink_activator) that doesn't attempt any of these workarounds - for cases where Vortex is run as admin anyway or if the workaround is already enabled by some other application or for Linux (native).
So if the deployment dropdown gives you a selection between "Symlink deployment" and "Symlink deployment (elevated)" (or only the former), you could just disable the "symlink_activator_elevated" extension, that will only lose the second option which you then don't need anyway.

**Comment by italoghost** [comment] 2022-02-05 16:47
@TanninOne I do not know if it is related but every time that I tried to launch Vortex after an installation I would receive this error:

![2022-01-30_20-09](https://user-images.githubusercontent.com/48540550/152650597-b0318437-179d-4c40-9ec0-e7fc09f6ac07.png)

Searching, [I found someone whom had a similar error and used these launch parameters to work](https://steamcommunity.com/app/1794680/discussions/0/3201496916539601709/):

```
1>/dev/null 2>/dev/null
```

After that I could launch Vortex without any problems.

**Comment by TanninOne** [comment] 2022-02-07 08:29
@italoghost No, that's a separate problem. This seems to be a fairly common issue between electron applications and linux (and even WSL) - when you run it from the ui rather than a terminal I guess?
It's not really anything we can fix I'm afraid, redirecting stdout and stderr like you did there is probably the best solution for the time being

**Comment by TanninOne** [comment] 2023-04-19 14:16
closing this because there doesn't seem to be anything to do on our end, please ping me if you disagree.

**Closed by TanninOne** 2023-04-19 14:16 UTC
Labels: bug :bug:
