### ISSUE TITLE
Cannot import Bethesda.net content Creation Club VR due to odd error

### ISSUE THREAD

**Issue by DaniDCAT** [Nexus-Mods/Vortex#12027] opened 2022-06-08 03:42 UTC
I am having problems importing the VR creation club content from Bethesda.net as this is the error I get when I attempt to install.

c:\Users\atthe\AppData\Roaming\Vortex\downloads\fallout4\Virtual Workshop: 	
              GNR-4134408-7.7z 		
              Desert Island-4135502-1.7z
              Atomic Crater-4135505-1.7z
              Grid World-4138281-1.7z
System ERROR: The filename, directory name or volume label syntax is incorrect

First time I imported this it glitched out and for some reason VR did not import properly
So deleted it and then reinstalled on Bethesda.net again and then attempted a second import.
This error popped up and it continues to do so even after multiple attempts.
This is the error I keep getting.
I have tried to scour all of my files and worked at deleting all sources through Vortex but so far I have found nothing that could be causing this issue.
I have tried importing in bulk and also one at a time.
Always this error.

Please help as this is the last of the Bethesda.net content and it is the only one causing me problems.

**Comment by DaniDCAT** [comment] 2022-06-08 06:44
Have just tried manually packaging the mods and inserting them in renamed folders into the mods directory. I will update if this is successful once I deal with all my mod cleaning but I would still hope for feedback on this.

**Comment by IDCs** [comment] 2022-06-08 06:46
@DaniDCAT - Normally, this only happens when the filepaths involved have characters which Windows sees as invalid. I can see that there's a colon ':' in the downloads folder you specified but I'm going to assume that you simply tried to specify that you're going to start enumerating the files which you can't import.

I'm assuming when you say "importing" you mean you're using the drag and drop functionality inside Vortex? or are you using the beth net import extension? (if the latter, you might want to report this to the extension developer @Pickysaurus) I'm afraid I can't help without seeing your log files and knowing exactly how you're importing the files.

You can find Vortex's log files inside `%appdata%/vortex`

**Comment by DaniDCAT** [comment] 2022-06-08 06:55
Beth Net import extension
sorry if that was not clear

Is it the file just named Vortex?

**Comment by IDCs** [comment] 2022-06-08 06:58
Any file named `vortex.log` or `vortex1.log`, etc.

As I mentioned, the Beth Net import extension is written by @Pickysaurus, I'll assign him to this ticket.

**Comment by DaniDCAT** [comment] 2022-06-08 07:00
I Hope this can help... I have quite a massive number of mods and am refining my list a bit but it is huge.

**Comment by Pickysaurus** [comment] 2022-06-08 08:55
After a bit of poking around, it seems you're trying to import the actual Creation Club mini-DLCs rather than mods. I don't own any of these so I'm not able to reproduce the issue.

**Comment by DaniDCAT** [comment] 2022-06-08 09:02
About to try after a hectic time downloading the files and my internet fighting me...

Will report on that next. But as for what you said I am confused a bit.

Is that a problem? It has an option to import them from the creation club.
Should I just ignore them?

**Comment by Pickysaurus** [comment] 2022-06-08 09:11
You can import then, but I can't really replicate the problem without also owning those DLCs.

**Comment by DaniDCAT** [comment] 2022-06-08 09:15
Well I guess I will just wipe them and leave the CC stuff on my bethesda.net part but here is a screen shot in case you run into someone else with this problem maybe you can reference this.
If not then thank you and sorry if this inconvenienced you
![Screenshot 2022-06-08 051413](https://user-images.githubusercontent.com/99364960/172579943-0552b97d-70a1-425a-ab78-dd74a41bc2e8.png)
!

**Comment by Pickysaurus** [comment] 2022-06-08 09:16
Ah, does the Virtual Workshop include several plugins? That might be the problem.

**Comment by DaniDCAT** [comment] 2022-06-08 09:17
The grid is the base mod that gives the VRWS the pod and such...
The other three are basically add on's to that so they could be considered plugins I guess.

**Comment by IDCs** [comment] 2022-07-04 09:05
Closing as this issue is directly tied to a 3rd party extension written by @Pickysaurus - please feel free to continue discussing it here, or use the extension page on the website.

**Closed by IDCs** 2022-07-04 09:05 UTC
Labels: waiting for reply
