### ISSUE TITLE
Can't login to Vortex

### ISSUE THREAD

**Issue by Raxdiam** [Nexus-Mods/Vortex#895] opened 2018-08-25 23:03 UTC
Since update 0.16.0, I have been unable to login to Vortex.
Here is a recording of what happens: [https://i.imgur.com/nbvboS0.mp4](https://i.imgur.com/nbvboS0.mp4)
Using the button in Vortex opens the default web browser, and asks me to authorize. After doing so, Vortex is brought to the front, but nothing changes.

Things I have tried:
- Using different web browsers. This includes Chrome, Firefox, Edge, and Internet Explorer.
- Uninstalling and re-installing Vortex.
- Deleting other associated data (by default what is in AppData\Roaming\Vortex).

Log file: [vortex.log](https://github.com/Nexus-Mods/Vortex/files/2321106/vortex.log)
OS: Windows 10 Pro

**Comment by TanninOne** [comment] 2018-08-27 08:16
This is purely a display error. You are correctly logged in, Vortex just doesn't update its UI to reflect that. If you close Vortex after logging in and restart it you should be logged in ok.

The reason this is happening is that in 0.16.0 we had to switch one of the external libraries we were using because the old one has been abandoned in a buggy state but the replacement works differently in a subtle way.
This could trigger other similar errors where part of the UI remains "outdated" until you do something else that forces an update of that component.

**Comment by wieser1955** [comment] 2018-08-27 09:55
Thanks for responding I had to reinstall to fix the problem but no big deal. thanks for the cool work your doing

**Comment by TanninOne** [comment] 2018-08-27 10:54
Turns out this wasn't at all what I thought it was. The "outdated UI" thing is a potential problem in 0.16 but not the cause of this error.
Actually it was just a line I had commented out for testing that somehow got committed. :(

**Closed by TanninOne** 2018-08-27 10:54 UTC
