### ISSUE TITLE
Trying To fix "failed to set game mode" error, nothing working.  

### ISSUE THREAD

**Issue by cheeseballzaregood** [Nexus-Mods/Vortex#14235] opened 2023-04-11 01:10 UTC
I'm on Windows 10, using Assasins Creed Origins on a new D drive, keep getting this:
"
SetupError: Missing: I:\Vortex Mods\Origins
    at C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:2921:145
    at tryCatcher (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:725:18)
    at _drainQueueStep (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:15:14)
"

attached is a video showing that vortex knows where the game is, and is right.  Thank you in advance and if anyone could help that would be great.

https://youtu.be/PWV59sd8Un0

**Comment by cheeseballzaregood** [comment] 2023-04-11 01:28
also uninstalled and reinstalled the game and verified files

**Comment by TanninOne** [comment] 2023-04-11 06:58
duplicate of #14232

**Closed by TanninOne** 2023-04-11 06:58 UTC
