### ISSUE TITLE
Open on Nexus Mods in the right click menu errors for archives

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/Vortex#6688] opened 2020-06-24 09:41 UTC
**Describe the bug**
Right-clicking an archive in the mods tab and selecting "Open on Nexus Mods" raises an exception. 
https://github.com/Nexus-Mods/Vortex/blob/master/src/extensions/nexus_integration/index.tsx#L809
https://forums.nexusmods.com/index.php?/topic/8844613-cannot-read-attribute-of-undefined/#entry82338208

**Expected behavior**
Open the Nexus Mods website.

**Comment by TanninOne** [comment] 2020-06-24 11:58
duplicate of #6634

**Closed by TanninOne** 2020-06-24 11:58 UTC
