### ISSUE TITLE
Suggestion – Conflicts between Engine Injectors and default mods

### ISSUE THREAD

**Issue by Novelyst** [Nexus-Mods/Vortex#10019] opened 2021-10-03 14:20 UTC
If one mod is a 'default' mod whereas another is an 'Engine Injector' and both contain the same file, conflicts will not be shown between them (and consequently Vortex will detect it as an external change when files are deployed).

This became a minor issue for me as I wanted to include files both in the game folder and in the mods folder and when deployed, Vortex would ask whether I wanted to overwrite a file from a 'default' mod as it had not detected the conflict. The easy solution to this is simply to make another, non-'Engine Injector' mod and include the file instead – it is just slightly less convenient.

It would be good if Vortex were able to detect conflicts between Engine Injectors and default mods.

**Comment by IDCs** [comment] 2021-10-04 06:56
duplicate of #5869

**Closed by IDCs** 2021-10-04 06:56 UTC
