### ISSUE TITLE
"Unexpected token � in JSON at position 0" & "Unexpected token � in JSON at position 1048576"

### ISSUE THREAD

**Issue by Tylhor** [Nexus-Mods/Vortex#4316] opened 2019-04-24 03:17 UTC
First of all, I should note I don't know much about programming and I am still very new to computers tech wise. 

Issue description: For some reason Vortex Mod Manager won't let me deploy or remove mods on Fallout 4 and Skyrim Special Edition. It'll just say fail to deploy mods, or failed to remove mods. Claiming either "Unexpected token  in JSON at position 0" or "Unexpected token  in JSON at position 1048576"
I've tried verifying and reinstalling the games and the problem still proceeds.

Expected Behavior: Mods should remove from Vortex when choosing to remove the mod file. Mods should be deployed when choosing to activate/deactivate them.

OS: Windows 10

Vortex Version: It started happening on version 1-0-14-1. I reinstalled Vortex version 1-0-17-11 and it's still occurring.

System Information:

 Time of this report: 4/24/2019, 13:02:47
             Machine name: DESKTOP-NGLB2V2
               Machine Id: {DC2C541D-427F-49C2-8B78-03485E1B75C1}
         Operating System: Windows 10 Pro 64-bit (10.0, Build 17134) (17134.rs4_release.180410-1804)
                 Language: English (Regional Setting: English)
      System Manufacturer: Alienware
             System Model: Alienware Area-51 R5
                     BIOS: 1.1.9 (type: UEFI)
                Processor: Intel(R) Core(TM) i7-7820X CPU @ 3.60GHz (16 CPUs), ~3.6GHz
                   Memory: 16384MB RAM
      Available OS Memory: 16264MB RAM
                Page File: 9145MB used, 11725MB available
              Windows Dir: C:\WINDOWS
          DirectX Version: DirectX 12
      DX Setup Parameters: Not found
         User DPI Setting: 96 DPI (100 percent)
       System DPI Setting: 96 DPI (100 percent)
          DWM DPI Scaling: Disabled
                 Miracast: Available, with HDCP
Microsoft Graphics Hybrid: Not Supported
           DxDiag Version: 10.00.17134.0001 64bit Unicode

These are my screenshots:

![Screenshot (1)](https://user-images.githubusercontent.com/49929167/56629889-7c689d80-6692-11e9-8532-e5082fd1c89b.png)

![Screenshot (4)](https://user-images.githubusercontent.com/49929167/56630502-f13cd700-6694-11e9-8153-e6373cd402bf.png)

![Screenshot (5)](https://user-images.githubusercontent.com/49929167/56630507-f6018b00-6694-11e9-83f0-e5658c705324.png)

Application Error:
 
System
  |  
-- | --
Platform | win32 10.0.17134
Architecture | x64
Application Version | 0.17.11
Process | renderer

Message
Unexpected token � in JSON at position 0.
*** When you report this, please include the file "C:\Program Files (x86)\Steam\steamapps\common\Fallout 4\data\vortex.deployment.json" ***

Title
Failed to deploy mods

Stack:

**Additional context**
Error: Unexpected token � in JSON at position 0.
*** When you report this, please include the file "C:\Program Files (x86)\Steam\steamapps\common\Fallout 4\data\vortex.deployment.json" ***
    at fs.readFileAsync.then.catch.err (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:1277:208)
    at tryCatcher (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:689:18)
    at Async._drainQueue (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:143:10)
    at Async.drainQueues (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:17:14)
    at <anonymous>

Application Error:

System
  |  
-- | --
Platform | win32 10.0.17134
Architecture | x64
Application Version | 0.17.11
Process | renderer

Message
Unexpected token � in JSON at position 1048576.
*** When you report this, please include the file "C:\Program Files (x86)\Steam\steamapps\common\Skyrim Special Edition\data\vortex.deployment.json" ***

Title
Failed to remove mods

Stack
Error: Unexpected token � in JSON at position 1048576.
*** When you report this, please include the file "C:\Program Files (x86)\Steam\steamapps\common\Skyrim Special Edition\data\vortex.deployment.json" ***
    at fs.readFileAsync.then.catch.err (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:1277:208)
    at tryCatcher (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:689:18)
    at Async._drainQueue (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:143:10)
    at Async.drainQueues (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:17:14)
    at <anonymous>

#

**Comment by IDCs** [comment] 2019-04-24 06:31
Hi @Tylhor, this is a known issue which is caused by corrupted Vortex manifest files. It usually occurs when Vortex is closed abruptly while writing to the manifest file, we've seen cases where this happened due to a power failure, BSOD, users turning off their desktop forcefully, etc.

We have taken steps to ensure this doesn't happen in future releases, but in your case I suspect that the manifest has been corrupted very early on (0.14.X, back when we had no countermeasures in place)

First of all, we suggest trying to validate your manifest file yourself using an online validator (https://jsonlint.com/ works quite well) and check whether it's possible to fix this manually.

If the file is corrupted beyond recovery please do the following:
1. Attempt to purge your current deployment (This may fail, but it's worth a shot)
![image](https://user-images.githubusercontent.com/8960252/56637078-a1451c80-6662-11e9-9e27-e00a03e73047.png)
2. Close Vortex
3. Delete the manifest file (C:\Program Files (x86)\Steam\steamapps\common\Skyrim Special Edition\data\vortex.deployment.json)
4. Start up Vortex and hit the deploy button
![image](https://user-images.githubusercontent.com/8960252/56636972-588d6380-6662-11e9-937d-e05ecfab2ce8.png)

That should fix it, please let us know if you encounter it again and try to give us a step-by-step guide for us to attempt to re-create it on our end.

(I'm going to leave this issue open for a couple of days until you're able to get back to us and confirm whether everything is working fine or not)

**Comment by TanninOne** [comment] 2019-04-24 07:04
duplicate of #524

**Closed by TanninOne** 2019-04-24 07:04 UTC
Labels: waiting for reply
