### ISSUE TITLE
Game request: Satisfactory

### ISSUE THREAD

**Issue by nosemage** [Nexus-Mods/Vortex#9909] opened 2021-09-11 01:41 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by nosemage** [comment] 2021-09-11 01:42
PLZ try to add satsfactory

**Comment by IDCs** [comment] 2021-09-14 06:18
Not going to lie, there are currently only 4 Satisfactory mods on the website so this game is very low priority on our end. You should try to convince members of the Satisfactory modding community to use NM to host mods and potentially develop a game extension for it.

**Comment by nosemage** [comment] 2021-09-14 23:33
ok

**Comment by TanninOne** [comment] 2021-09-28 13:55
duplicate of #7955

**Closed by TanninOne** 2021-09-28 13:55 UTC
Labels: game request
