### ISSUE TITLE
Consider marking the ENB and Dinput mod types as non-deployment-essential

### ISSUE THREAD

**Issue by agc93** [Nexus-Mods/Vortex#9665] opened 2021-07-19 06:19 UTC
**Describe the bug**
The context on this issue is ZGal88 working on an extension for Grounded which is also available through Game Pass. In the case where it's installed from the MS Store, the game directory will be read-only and up to the usual MS Store filesystem trickery.

*However*, Grounded (like a lot of UE4 games) can load mods from the user's AppData folder without writing to the game directory at all. Even if the extension registers the game with a `queryModPath` outside of the game directory, the `dinput` and `enb` mod types will still match as supported and fail since the installation directory is not writeable. At that point, no deployment method becomes available and you're in an invalid state.

Now I've started working on a way for the dinput and enb mod types to use a named key from the `IGame.compatible` object, but it occurs to me that just making these mod types non-deployment-essential with `IModTypeOptions.deployEssential` could presumably avoid this issue as well?

**To Reproduce**
1. Register a game with a read-only game directory but a writeable mods path
2. No deployment method will be available as the dinput/ENB mod types fail to pass
3. Disable those two mod types
4. Deployment methods become available again

**Expected behavior**
The dinput and ENB mod types failing to be deployable shouldn't prevent a game from completely being undeployable.

**Platform (please complete the following information):**
 - OS: Windows 10
 - Vortex Version 1.4.14

**Additional context**
To be clear, I'm also happy to just finish off the method I started (using `IGame.compatible`), but is there a reason dinput and ENB are considered deployment essential at the moment, that I'm not thinking of?

**Comment by zgal88** [comment] 2021-07-19 06:34
*waves hand*

Yes hello, that would be me.
To add to the above, though it makes likely zero difference, is that it was tested on both same-drive and secondary/tertiary drive installations, with the game installation, AppData/mods folder, and vortex staging folder, being on different drives, and same-drive setups. No combination of the above was able to overcome the issue, and once the two extensions mentioned above were disabled, I was able to get all of the aforementioned combinations to work perfectly.

**Comment by IDCs** [comment] 2021-07-19 06:43
Hey there - `IModTypeOptions.deploymentEssential` is indeed meant to be used to stop certain modTypes from blocking the availability of certain deployment methods. Weirdly we did not use this feature before, but I agree that ENB and dinput should probably have that assigned to them by default. @TanninOne is there a reason why we didn't set the deploymentEssential flag to false on those modTypes ?

**Comment by TanninOne** [comment] 2021-07-19 10:16
The problem is that these mod types (dinput specifically) may be essential for certain games, e.g. for GTA V modding, the script hook being installed (to the base game directory) is essential for modding to work as expected.
Marking the mod type as "non essential" entirely would mean that users would not get an error message (and consequently no suggestion on how to fix it) when their setup is not actually working.
Thus it would also count as a breaking api change which we can't do within a minor update anyway.

Using the compatible flag for this is the better solution imho because it gives us the required amount of configureability without risk of breaking existing game extensions.

**Comment by zgal88** [comment] 2021-07-19 10:36
Is there a way, via the game extension, to mark the two types as incompatible with the game? It seems like it would simply require skipping the pass/fail for those two types, for the deployment options.

**Comment by IDCs** [comment] 2021-07-19 10:56
> Is there a way, via the game extension, to mark the two types as incompatible with the game? It seems like it would simply require skipping the pass/fail for those two types, for the deployment options.

That's actually what @agc93 proposed - game extensions can provide compatibility information through the `IGame.compatible` property (you can define that when you call the `registerGame` function) - we currently use that property to define whether a deployment method is compatible with the game; he's suggesting we use it for modTypes as well.

@agc93, your post suggests that you've already started modifying the dinput and enb modTypes and are planning to submit a PR ? (Just checking to ensure we don't duplicate efforts)

**Comment by IDCs** [comment] 2021-07-21 14:25
All merged - again, thanks for your help @agc93

**Closed by IDCs** 2021-07-21 14:25 UTC
