### ISSUE TITLE
Synthesis not working in recent Vortex versions.

### ISSUE THREAD

**Issue by alderwyn** [Nexus-Mods/Vortex#13200] opened 2022-09-29 16:17 UTC
**Describe the bug**
Synthesis specifically won't start. All the other tools I add work. I already contacted Synthesis support and Vortex used to work with it but now it doesn't. Synthesis doesn't generate any logs, it just shows the loading logo for one second then nothing. Vortex gives the error "failed to run tool". Images of the full error (hosted by Discord) provided in the screenshots section.

**To Reproduce**
Steps to reproduce the behaviour:
1. Download  the latest version of Synthesis from [HERE](https://github.com/Mutagen-Modding/Synthesis/releases).
2. Add it as a tool.
3. Run the tool.
4. See error.

**Expected behaviour**
The expected behaviour is for Synthesis to start without error.

**Screenshots**
[Run error part 1](https://cdn.discordapp.com/attachments/1024784769617244261/1024784769751449621/Screenshot_2022-09-29_064637.png)
[Run error part 2](https://cdn.discordapp.com/attachments/1024784769617244261/1024787785422483506/unknown.png)

**Platform (please complete the following information):**
 - OS: Windows 11
 - Vortex Version: Latest Stable from the date of this post.

**Additional Issues**
The send feedback button in the widget does nothing. I can use the send feedback button in the triple dot menu beside my profile picture but then submit feedback doesn't work.

**Comment by gregest** [comment] 2022-10-01 21:47
Can also confirm that I'm experiencing the same issue that did not happen before, with letter to letter the same exact error

**Comment by TanninOne** [comment] 2022-10-04 08:16
This is caused by a change introduced with 1.6.11, will be fixed in the next release.  For now, best run the tool from outside Vortex.

**Comment by TanninOne** [comment] 2022-10-06 11:49
Should be fixed in 1.6.14

**Closed by TanninOne** 2022-10-06 11:49 UTC
