### ISSUE TITLE
Application Repeatedly Whitescreens and Restarts at Startup (same issue from 2019 appearing again)

### ISSUE THREAD

**Issue by MaximusFullius** [Nexus-Mods/Vortex#15752] opened 2024-05-21 20:18 UTC
**Describe the bug**
I'm getting the same issue as this other guy from 2019: https://github.com/Nexus-Mods/Vortex/issues/5524
Basically, when I try to start Vortex, the application screen just keeps going white and the app keeps restarting itself every second or so. I've already tried everything mentioned in the post, including reinstalling, installing old versions, and restarting my computer, but it still doesn't work. The only way I can get Vortex to launch at all is when I apply the janky fix mentioned by Saipher604 in the comments of the post, where I have to go into C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar.unpacked\bundledPlugins and delete every game file except the ones I'm actually using. After doing this, I get an error message from Vortex saying the installation has been "corrupted", but then the application actually launches, so I'm not complaining there. 

**To Reproduce**
1. Install the latest version of Vortex and attempt to launch the game. 

**Expected behavior**
Screen goes white and the application restarts itself in approx 1 second intervals.

**Screenshots**
![image](https://github.com/Nexus-Mods/Vortex/assets/12753462/31afcdd2-f3f4-40cb-bf80-1b8dec9e1b61)

**Platform (please complete the following information):**
 - OS: Windows 10
 - Vortex Version: latest (1.11.5)

**Additional context**
I've had Vortex for a while and I've been using it with other games in the past, but it's not even launching anymore unless I delete all the other game files in C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar.unpacked\bundledPlugins for games I don't have.

**Comment by IDCs** [comment] 2024-05-22 06:12
Hey @MaximusFullius - thanks for your report.

Can you perhaps try to see which bundled game extension produces the whitescreen? Perhaps Witcher 3?

Can you also tell us which game stores you are using (all of them) so I can see if our game store extensions are potentially blocking Vortex's startup.

**Comment by MaximusFullius** [comment] 2024-05-25 17:10
> Hey @MaximusFullius - thanks for your report.
> 
> Can you perhaps try to see which bundled game extension produces the whitescreen? Perhaps Witcher 3?
> 
> Can you also tell us which game stores you are using (all of them) so I can see if our game store extensions are potentially blocking Vortex's startup.
> 
> Please remember to tag me in your response, otherwise I may miss it completely (I have over 200 notifications on a daily basis)

The Vortex application fully launches only when the game bundle files for the Witcher 3, fallout new vegas, and cyberpunk 2077 exist in the relevant Vortex folders (I forget what file path they're in exactly, and I've uninstalled vortex to use Mod Manager. I remember the files all had the format "game-X". So to answer your question, it seems **all of the game files except the Witcher 3, Fallout New Vegas and Cyberpunk 2077 are causing the whitescreen.**

**Comment by MaximusFullius** [comment] 2024-05-25 17:11
In previous versions of Vortex, I only had mod profiles for those three games (the Witcher 3, Fallout New Vegas and Cyberpunk 2077) active, so perhaps Vortex is crashing looking for mod profiles that aren't there?

**Comment by MaximusFullius** [comment] 2024-05-25 17:16
I've also used vortex for other games in the past like fallout 4, skyrim and skyrim special edition, but those profiles should all be deleted by now.

**Comment by IDCs** [comment] 2024-06-05 07:01
Hey @MaximusFullius - sorry for taking so long to respond (you forgot to tag me 😆)

Can you please go to your `%appdata%/vortex` folder and send me all of your `vortex.log/vortex.txt` files and attach them here.

The problem with manually modifying the bundled extensions is that it becomes very difficult for us to debug whether this is caused by a missing extension or something else. To add to this - installing older versions of Vortex can corrupt your application state beyond repair as the older versions may have had significant bugs in them which are now fixed.

One thing that might be worth trying - use the disk cleanup Windows utility to clear your temp folder and see if that fixes it.

Unfortunately given your use case, I can't reliably ascertain whether switching to older versions of Vortex may have corrupted your state. But I hope your logs may give me more information.

**Comment by IDCs** [comment] 2024-07-30 08:09
Issue is stale - closing

**Closed by IDCs** 2024-07-30 08:09 UTC
Labels: waiting for reply
