### ISSUE TITLE
Please add bain and omod support

### ISSUE THREAD

**Issue by darkx239** [Nexus-Mods/Vortex#11025] opened 2022-02-13 03:44 UTC
**Is your feature request related to a problem? Please describe.
I'm always frustrated when I can't use bain and omod installers

**Describe the solution you'd like**
I would like bain and omod support added

**Describe alternatives you've considered**
None

**Additional context**
N/A

**Comment by TanninOne** [comment] 2022-02-14 13:55
duplicate of #406 and #95

**Closed by TanninOne** 2022-02-14 13:55 UTC
Labels: enhancement
