### ISSUE TITLE
I accidentally closed the previous one: Vortex changing files to and from .vortex_lnk over and over

### ISSUE THREAD

**Issue by ladyaurora1ca** [Nexus-Mods/Vortex#1120] opened 2018-10-02 05:14 UTC
The only way I have managed to fix this so far is to purge all mods and then redeploy them all at the same time, otherwise I end up with the below problem continuing.

Every file I install and every deployment Vortex says that files from outside Vortex were changed even when they weren't. It also doesn't matter if I save changes or revert, as the files in the folders switch between what they are (esp, esl, esm, nif, etc) to the filename.vortex_lnk. I've watched it happen in my files no matter if I revert or not. I did revert multiple times in a row and this still happened. Due to this happening throughout every single time I deployed, I now have a mixture of .vortex_link files and regular files.

**Comment by IDCs** [comment] 2018-10-02 09:55
Hi @ladyaurora1ca, thanks for reporting this issue. *.vortex_lnk files are created when the user selects the experimental "move deployment" method. Could you please confirm whether you've selected this setting yourself or whether Vortex has been using it by default ?

Also please let us know which version of Vortex you were using when you encountered this behavior.

**Comment by IDCs** [comment] 2018-10-02 10:07
![image](https://user-images.githubusercontent.com/8960252/46342644-3b943300-c633-11e8-8ca4-84090a280d3b.png)

**Comment by ladyaurora1ca** [comment] 2018-10-02 15:12
Version: Vortex 0.16.5, Windows 10,

It was in Move Deployment. I had not selected the option.

**Comment by IDCs** [comment] 2018-10-04 13:27
Hi @ladyaurora1ca, we suspect your issue was caused by a bug which did not clean Vortex's deployment information file correctly (fixed in https://github.com/Nexus-Mods/Vortex/commit/29b4f18750b4cf466f373adf54e17f2f0ac62864). 

Once presented with the external changes dialog, clicking the save button would unfortunately remove the files completely from the machine, leaving only the *.vortex_lnk files behind in Vortex's appdata folder. At that point, whenever you would click the "deploy mods" button, Vortex would deploy the vortex_lnk files to your game's mods folder as the original mod files were no longer on the machine.

To confirm whether your Vortex appdata folder has been affected by this, please have a look at your C:\Users\"YourUserName"\AppData\Roaming\Vortex\skyrimse\mods folder, and ensure that the mods inside that folder do not contain *.vortex_lnk files.

**Comment by IDCs** [comment] 2018-10-04 13:55
Hi @ladyaurora1ca, we suspect your issue was caused by a bug which did not clean Vortex's deployment information file correctly (fixed in https://github.com/Nexus-Mods/Vortex/commit/29b4f18750b4cf466f373adf54e17f2f0ac62864). 

Once presented with the external changes dialog, clicking the save button would unfortunately remove the files completely from the machine, leaving only the *.vortex_lnk files behind in Vortex's appdata folder. At that point, whenever you would click the "deploy mods" button, Vortex would deploy the vortex_lnk files to your game's mods folder as the original mod files were no longer on the machine.

To confirm whether your Vortex appdata folder has been affected by this, please have a look at your C:\Users\"YourUserName"\AppData\Roaming\Vortex\skyrimse\mods folder, and ensure that the mods inside that folder do not contain *.vortex_lnk files. If you do have any of those files, please uninstall the mod from within Vortex and then re-install it; that should re-instate the original mod files.

Important note, to avoid problems like this completely we recommend using hardlink deployment as it's less prone to errors like this. Vortex defaulted to the move deployment instead of hardlink due to one or more of the following reasons:
- The game's mod path lacked write access -> Rectifiable by removing the "read-only" flag from the mod path and files.
- Mods are installed on a different disk drive than the game -> You can go to Vortex's settings and change the mod directory to the same drive as the game.
- Vortex delete operations are blocked by anti-virus software -> Add an exception to your anti-virus to ignore Vortex.

Finally, regarding the move deployment fix I mentioned above, it will be included in Vortex versions 0.16.9 (not yet released at time of writing) and above. I'm going to close this issue for now, please do let us know if you encounter this issue again in future versions.

**Closed by IDCs** 2018-10-04 13:55 UTC
Labels: bug
