### ISSUE TITLE
Regression: Check for mod updates does not work anymore

### ISSUE THREAD

**Issue by brazenvoid** [Nexus-Mods/Vortex#4544] opened 2019-05-26 19:22 UTC
**Describe the bug**
Check for mod updates, since the recent performance update has not been able to find any mod updates.

**To Reproduce**
1. Run Check for Mod Updates
2. No new updates are detected
3. Go to download history on website and sort mods by update date
4. See the new updates

**Expected behavior**
Just make it work as it did before.

**Platform**
 - Game: Fallout 4
 - OS: Windows 10 1809
 - Vortex Version 0.18.4

**Additional context**
Currently my account has about 4 new updates listed which in no way are getting detected by vortex:
Apocalyptic Commonwealth v1.2 (I have v1.1)
RobCo Recon Scope Replacer v1.03 (I have v1.02)
Sim Settlements v4.0.8 (I have v4.0.7a)
Sim Settlements Conqueror v4.0.8 (I have v4.0.7b)

**Comment by TanninOne** [comment] 2019-05-27 07:39
Can't reproduce, could you please send in a feedback and attach your application state (under "Attach Special File")?

**Comment by brazenvoid** [comment] 2019-05-27 11:14
I submitted a report then.

**Comment by TanninOne** [comment] 2019-05-27 11:40
In the report you sent in all mods you mentioned are up-to-date, e.g. Sim Settlements is at 4.0.8, not 4.0.7.

**Comment by brazenvoid** [comment] 2019-05-27 15:52
Of course they will be, I updated them manually.

**Comment by brazenvoid** [comment] 2019-05-27 16:00
Fortunately today there is another update which is not getting detected through vortex;
This mod: (I have v1, new one is v2)
https://www.nexusmods.com/fallout4/mods/38833

**Comment by TanninOne** [comment] 2019-05-28 09:25
Please send in an application state that still exposes the problem, meaning one where you still _have_ a mod that doesn't report an update even though there is one.

**Comment by brazenvoid** [comment] 2019-05-28 13:21
Sent. I haven't updated yet and its still not detecting anything.

**Comment by TanninOne** [comment] 2019-05-28 15:20
Thanks, this helped narrow it down.
The mod was updated 27 May 2019, 8:24 pm as it says in the download history, do you remember how long after that you checked for updates in Vortex the first time?
I think this error is probably caused by the server giving Vortex outdated update information.

**Comment by brazenvoid** [comment] 2019-05-28 15:22
The first time I checked roughly was a the same time as I messaged yesterday. I even checked now, and its still not showing up as having any updates.

**Comment by Grestorn** [comment] 2019-05-29 13:38
Addition to my report: 

Originally I had this problem while at least one mod could not be checked ("Boys of Summer", the author has removed that mod). 

I resolved that by removing Nexus as a source for that mod. But checking didn't work at first, but now it actually is working for me again. Maybe a restart of Vortex resolved it? I also update a number of mods manually last time I had been using Vortex, that could also make a difference.

Now I get the progress bar (which wasn't there the last time I tried) and the notice, that the check has been completed. And one new update notification.

**Comment by brazenvoid** [comment] 2019-05-29 14:55
So today too its not detecting anything. Please add some appropriate tag other than "waiting for reply" or I will keep updating this issue now and then.

**Comment by Grestorn** [comment] 2019-06-01 07:05
Now it doesn't work anymore once again. 

I've got almost 300 active mods, when I click "Check for updates", it just takes about 3 seconds until the "Check for mod update finished" popup appears. No progress bar, whatsoever.

Updated mods it missed in my installation: "The people of skyrim 2" (22392) , "Forgotten Retex Project" (7849), "Apocalypse" (1090), "Nether's Follower Framework" (18076)

**Comment by TanninOne** [comment] 2019-06-04 06:34
Just to clarify: The check is indeed expected to be _much_ faster. Previously Vortex had to send out a request to the api for every mod you have installed, now it sends out a single request and then another one for the mods that actually have been updated.
We're still investigating why it's missing some updates.

**Comment by anakhasilver** [comment] 2019-06-04 14:46
I'm also having the issue with it not detecting updates.

Nothing is updating and I found out that a lot of mods have updated. I have 0.18.6 and previously 0.18.5, on a Windows 10 OS. It's a new computer, so I have plenty of memory--like, a whole TB. So it's not that. It's just not detecting mod updates.

**Comment by TanninOne** [comment] 2019-06-11 14:22
0.18.7 (currently in testing) has an option to force the full (unoptimised) check as it was done before 0.18.6.
Please let us know if this check now finds the updates you were missing.
Also, please keep us updated on whether the optimised check works reliably after you've done a forced full check in 0.18.7.

**Comment by Red-Can** [comment] 2019-06-12 03:10
After using "check for Update(Full)" on Vortex Version 0.18.7, It reports "Full update found no updates that the regular check didn't".

Attached diagnostic file and screenshot. My current installed version of Settlement Repair Bot is versio 1.2 and [version 2.0 was uploaded on 11 June 2019 5:14PM](https://www.nexusmods.com/fallout4/mods/37933).


![vortex](https://user-images.githubusercontent.com/38169213/59320780-22995280-8c95-11e9-80ce-165143065df8.jpg)
.

[Update fail.txt](https://github.com/Nexus-Mods/Vortex/files/3279380/Update.fail.txt)

**Comment by brazenvoid** [comment] 2019-06-12 03:13
The optimized check found an update for the first time with 0.18.7. I will keep checking.

**Comment by Red-Can** [comment] 2019-06-12 04:52
After reading the above post from [bravenvoid](https://github.com/brazenvoid), the "Check for Updates(Optimized)" did find an update for Even Better Mod Descriptions. But it did not show the update for Settlement Repair Bot, that I used as an example in my previous post.

**Comment by TanninOne** [comment] 2019-06-12 07:16
@Red-Can Vortex doesn't check mods more than once an hour and it can only check mods that have a Source of "Nexus Mods". When you did that log no files where checked at all because they were all either checked less than an hour ago already or they don't have the source set.
@Grestorn Thank you for the log. If this happens again, please be sure to send it again.

**Comment by TanninOne** [comment] 2019-06-12 10:06
HouseOfBlues: Same as Red-Can: The full check skips all of your mods because they have been checked within the last 60 minutes. Wait a bit then try again.

**Comment by Red-Can** [comment] 2019-06-12 12:05
TanninOne thank you, I did not know about the 1 hour delay. I just checked and got :

![vortex2](https://user-images.githubusercontent.com/38169213/59349681-dfb09c80-8cdf-11e9-90c1-93853ab6f84a.jpg)
[Update fail.txt](https://github.com/Nexus-Mods/Vortex/files/3281188/Update.fail.txt)

**Comment by Les4845** [comment] 2019-06-13 13:34
Vortex Version: 0.18.8
Memory: 32 GB
System: Windows 10 Pro 1903(18362.145)
Vortex no longer retrieves metadata to update mods.
Ran a full update and it found 3 updates 'wouldn't have found doing normal search'. I have included Vortex log and network log as requested.

**Comment by TanninOne** [comment] 2019-06-17 09:42
Thanks to everyone who sent in logs, please keep them coming.

**Comment by TanninOne** [comment] 2019-06-25 11:59
@supra728 Your case is super-weird.
The mods in question are "Immersive Armours" and "Immersive Patrols". Vortex thinks they have been checked for updates on "06/15/2019 @ 5:13pm (GMT)" - exact same time to the millisecond.
Yet according to the log Vortex wasn't even running at that time.
Do you remember if you checked for updates around that date or manually installed mods or anything?

**Comment by supra728** [comment] 2019-06-25 12:23
Hi,

The day I sent the logs was the first time I'd started it in a while, so I
don't think it was active then?

**Comment by TanninOne** [comment] 2019-08-28 15:10
Why would you reformat? If you encounter this problem you just run the full check from time to time.

Also: We're specifically asking users to send in a report when the full check finds updates that the regular one doesn't. I don't think we've received such a report an a month so either the last update fixed this or no one cares about this problem. At least not enough to click a button.

**Comment by brazenvoid** [comment] 2019-08-28 16:33
As for my particular case, I haven't found a missed update since sometime now.

**Comment by TanninOne** [comment] 2019-08-28 16:38
If the full update doesn't find the updates either then this is an unrelated issue.

The most likely reason is that the mods you're referring to aren't providing proper information to discover the updates. Providing the names of the affected mods would probably have solved this very easily, deleting and reinstalling everything was almost certainly an overreaction and a massive waste of your time.

**Comment by TanninOne** [comment] 2019-09-05 10:53
I'm going to close this since the lack of reports (of the actual issue) indicates the problem is resolved.

**Closed by TanninOne** 2019-09-05 10:53 UTC
Labels: bug, cant reproduce
