### ISSUE TITLE
X4 Foundations path to mods folder not type string.

### ISSUE THREAD

**Issue by yggdrasil75** [Nexus-Mods/Vortex#5052] opened 2019-07-09 02:01 UTC
When Changing paths for X4: Foundations get an error that path argument is not of the type String.

**Platform (please complete the following information):**
vortex version .18.12
steam version of X4
Windows version: windows 7 professional x64 sp1

**Additional context**
https://pastebin.com/tPWHeCJs
latest log. 
This issue was created based on information provided by Rhiwaow#2190 (244503610753286145) on Nexus discord.

**Comment by IDCs** [comment] 2019-07-09 06:44
duplicate of #4992

**Closed by IDCs** 2019-07-09 06:44 UTC
Labels: duplicate
