### ISSUE TITLE
error: Log-in connection closed prematurely (Code 1006)

### ISSUE THREAD

**Issue by Teishimeikato** [Nexus-Mods/Vortex#2130] opened 2018-11-10 04:41 UTC
**Describe the bug**
Servor refuse connection to Vortex

**To Reproduce**
1. Go to Vortex
2. Click on Red icone or offers connection by Vortex
3. Wait a result

**Expected behavior**
I see notification expected servor refuse connection to Vortex each log 

**Platform (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Vortex Version [e.g. 0.16.12]

**Additional context**
I'm so sorry for my english but i'm french and my english is very bad. I training me for improve.

**Comment by TanninOne** [comment] 2018-11-10 10:05
duplicate of #2063

**Closed by TanninOne** 2018-11-10 10:05 UTC
