### ISSUE TITLE
Vortex will not install some mods in a collection for free users.

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/Vortex#15991] opened 2024-06-24 14:43 UTC
**Describe the bug**
Vortex does not start the download for mods in a collection where they are both using an archived version from Nexus Mods and using the "Replicate" install type. 

**To Reproduce**
1. Be a free user.
2. Manage Cyberpunk 2077
3. Add this collection https://www.nexusmods.com/cyberpunk2077/mods/4197
4. Click "Later" to avoid installing all mods.
5. In the collection view find TweakXL 1.8.5 and click install.
6. Follow the prompts on the website to start the download.
7. No download is started.

**Expected behavior**
The mod installs correctly

**Screenshots**

https://github.com/Nexus-Mods/Vortex/assets/31670524/3bc6df58-5a72-4161-9dc6-76b85f6e9162

**Comment by Pickysaurus** [comment] 2024-06-24 14:44
```
2024-06-24T14:23:23.908Z [DEBUG] no download found {"ref":"{\"description\":\"TweakXL\",\"fileMD5\":\"646bc22d585c9a0a8b8b7290c1b9ee63\",\"gameId\":\"cyberpunk2077\",\"fileSize\":577039,\"versionMatch\":\"1.8.5\",\"logicalFileName\":\"TweakXL\",\"tag\":\"ZVViqLm4jn\",\"repo\":{\"repository\":\"nexus\",\"gameId\":\"cyberpunk2077\",\"modId\":\"4197\",\"fileId\":\"76091\",\"campaign\":\"collection\"}}"}
```

**Comment by IDCs** [comment] 2024-06-25 08:59
closed by mistake

**Comment by z9er** [comment] 2024-06-25 15:58
This is also happening with that collection with a hidden mod we include: 

https://www.nexusmods.com/cyberpunk2077/mods/10426

with the currently included version 1.8.3 on revision 467 of https://next.nexusmods.com/cyberpunk2077/collections/iszwwe

**Comment by IDCs** [comment] 2024-06-26 12:47
As I mentioned on Discord - I've downloaded the entire collection as a free user (both revision 467 and 466) without being able to reproduce this issue. The collections code hasn't changed in months - this is far more likely to be down to some sort of network issue or potentially the backend servers acting up, not Vortex.

Vortex literally just sends a request and gets a link back from the backend which it then uses to download the mod files, if for whatever reason that link is corrupted, then the download will indeed fail but that's out of Vortex's control.

As @Pickysaurus also mentioned, he's now able to download the file he mentioned in the collection just fine, which suggests my analysis is correct.

Going to leave the ticket open for now just in case we're able to consistently reproduce this again for the sake of forwarding this to the backend team when it does happen.

**Comment by IDCs** [comment] 2024-06-26 13:41
Thanks @z9er, as suspected it was a backend issue - looks like there were some permission issues on the Singapore CDN which should now be fixed. Please let any users that are still affected to try again and let us know if they're now able to download the files correctly.

**Comment by IDCs** [comment] 2024-06-27 05:21
Users have confirmed this is now fixed - thanks again for the report - closing.

**Closed by IDCs** 2024-06-27 05:21 UTC
Labels: cant reproduce
