### ISSUE TITLE
Vortex 1.9.10

### ISSUE THREAD

**Issue by OldGamerDarthyOfficial** [Nexus-Mods/Vortex#14961] opened 2023-12-05 09:20 UTC
After Reinstalling the App on My M2, the App ask to PC more Resources and Download of Extensions is Stuck but my PC is Ryzen 7900X and 64GB DDR5 6000 Mhz Ram the M2 is 4TB ... ah! the Interface has a FXAA Big Problems with Highs DPI Monitor or Very Good GPU exaple i have RTX 4090 and After FXAA Manual Diable on Vortex the Works Good but Only for Read Problems 
![Screenshot 2023-12-05 101835](https://github.com/Nexus-Mods/Vortex/assets/141849277/a1537054-395f-4082-a461-d66c3844ad5a)
P.S. 1000 MBPS Download an 300MBPS UPLOAD... :( i Try to Reinstall the 1.9.10 but if not Fix i back on 1.9.9 or 1.9.7 :(

**Comment by IDCs** [comment] 2023-12-05 10:35
Hi there @OldGamerDarthyOfficial

Could you please attach your `vortex.log` files and any `network.log` files which can be found inside `%appdata%/Vortex` ?
I don't think this has anything to do with 1.9.10, it's much more likely to be a network drop.

Can you please cancel those downloads and try to re-download the extensions?

**Comment by IDCs** [comment] 2023-12-07 14:08
Closing this as any sort of rendering issue is caused by theme-ing or hardware issues on the user's end. Electron bug report references are welcome!

**Closed by IDCs** 2023-12-07 14:08 UTC
