### ISSUE TITLE
"Warn" log-level events aren't viewable inside Vortex in the "Diagnostics Files" section

### ISSUE THREAD

**Issue by Hobadee** [Nexus-Mods/Vortex#6704] opened 2020-06-25 05:45 UTC
**Describe the bug**
"Warn" log-level events aren't viewable from inside Vortex in the "Diagnostics Files" section.  The log entries do exist in the actual log files.

**To Reproduce**
1. Create an extension, plugin, or something else and use the `log()` function to produce a warning level log entry.  In JS, this may be done as so:
`log('warn', 'FINDME');`
2. Load Vortex and trigger the function with the log message to run.
3. In the top-right of Vortex, click the 3 dots then "Diagnostics Files"
4. Open the appropriate diagnostic file.
5. Uncheck all levels except "WARNING".  Nothing will appear.
6. Check the actual log file (in Notepad or similar) to verify the "warning" level events exist.  (They do)

**Expected behavior**
The log viewer in Vortex should display Warning level logs.

**Screenshots**
![image](https://user-images.githubusercontent.com/3672739/85662784-2e23a580-b66d-11ea-8b33-4f0265d68d77.png)

**Platform**
 - OS: Windows 10
 - Vortex Version: 1.2.17

**Comment by TanninOne** [comment] 2020-06-25 06:23
duplicate of #6611

**Closed by TanninOne** 2020-06-25 06:23 UTC
