### ISSUE TITLE
ERRORCODE installation failed c000135

### ISSUE THREAD

**Issue by matthew4216** [Nexus-Mods/Vortex#11960] opened 2022-05-26 04:22 UTC
**Describe the bug** Installation bug
I don't know what the bug is. I've tried to look it up but no one could explain it.
**To Reproduce**
1. Go to '...' vortex
2. Click on '....' mods
3. Scroll down to '....'  pet/feed dogmeat
4. See error installation failed

**Expected behavior**
As normal I expected to after re install to fix the issue but i keep getting the same error, It will load the fallout4se just fine.

**Screenshots**

**Platform (please complete the following information):**
 - OS: [e.g. Windows 10] windows 11 pro
 - Vortex Version [e.g. 0.16.12] 1.5.13

**Additional context**
![20220525_231629](https://user-images.githubusercontent.com/106294244/170414987-34ff504a-70f6-4238-985b-1c0d81eed859.jpg)

**Comment by IDCs** [comment] 2022-05-30 11:03
duplicate of #8359

**Closed by IDCs** 2022-05-30 11:03 UTC
