### ISSUE TITLE
Failed to set game mode - new issue

### ISSUE THREAD

**Issue by dyonkus** [Nexus-Mods/Vortex#13580] opened 2022-11-30 15:20 UTC
**Describe the bug**
Will not let me mod either spider-man game.

**To Reproduce**
Not sure. I clicked "manage" on either spider-man game and got this same error. Issue presents itself after I click "download and install" on the prompt to install the SMPC modding tool. Now, it says it's managed, but when I click "activate", the issue presents itself again.
![Screenshot 2022-11-30 102322](https://user-images.githubusercontent.com/79821005/204838078-03426fb7-75ad-494c-ba78-fb5ca9448b89.png)
![Screenshot 2022-11-30 102357](https://user-images.githubusercontent.com/79821005/204838223-821a3f7d-85cd-4c88-9b82-019eccad0299.png)

**Expected behavior**
I guess it should let me mod the games?

**Screenshots**

**Platform (please complete the following information):**
 - OS: Windows 11
 - Vortex Version 2.0.2

**Additional context**
TypeError: Cannot read properties of undefined (reading 'filter')
    at C:\Users\dyonk\AppData\Roaming\Vortex\plugins\Vortex Extension Update - Spider-Man Remastered and Miles Morales Support v2.0.2\index.js:763:14
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\dyonk\AppData\Roaming\Vortex\plugins\Vortex Extension Update - Spider-Man Remastered and Miles Morales Support v2.0.2\index.js:622:58)
    at tryCatcher (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:15:14)

**Comment by TanninOne** [comment] 2022-12-01 12:45
duplicate of #13578

**Closed by TanninOne** 2022-12-01 12:45 UTC
