### ISSUE TITLE
Vortex unable to launch

### ISSUE THREAD

**Issue by popsoda27** [Nexus-Mods/Vortex#7201] opened 2020-08-13 11:32 UTC
**Describe the bug**
Refer to screenshot. Appears each time trying to run the program.

**To Reproduce**
1. Dbl click on desktop shortcut
2. Run from Start menu shortcut
3. Run exe directly from program folder
All 3 gives the same error

**Expected behavior**
To launch into the program as per normal

**Screenshots**
![Annotation 2020-08-13 184418](https://user-images.githubusercontent.com/20932783/90129227-d830cb80-dd9a-11ea-9ef3-a0ddb084bd02.png)

**Platform (please complete the following information):**
 - OS: Win 10 64bit Build 18363
 - Vortex Version 1.2.20

**Additional context**
Already tried uninstalling and reinstalling. Also reinstalled java se 8 runtime if that helps at all.

**Comment by IDCs** [comment] 2020-08-13 12:03
Hi @popsoda27, looks like one of our native libraries failed to load on your system... I can see that you've used our custom installer; can you please try installing Vortex using the default installer instead and see if that helps ?

**Comment by popsoda27** [comment] 2020-08-13 12:57
Thank you. It does work now using the default installer. Only con is I can't choose where to install Vortex

**Comment by IDCs** [comment] 2020-08-13 13:04
Hey @popsoda27, glad to hear it works - well the Vortex installation itself is located inside "C:\Program Files\Black Tree Gaming Ltd\Vortex" and shouldn't take more than ~300MB all other directories are highly customizable; so you can go to your Settings tab and choose to store your downloads or staging folders in "D:\". Please keep in mind that the downloads folder is used for all games, while staging folders are on a per-game basis.

It's really odd that the custom installer was causing you trouble, I literally just spinned up a virtual machine with a fresh install of windows 10 and used the custom installer to re-create your use case and it ran just fine.. There must be something weird about your environment. Can you think of any issues you've recently had with your PC when using other applications ? or anything that might shed some light on why the custom installer is having issues ?

**Comment by IDCs** [comment] 2020-08-13 13:06
Do you have an Anti Virus installed? if so what brand and what version ?

**Comment by popsoda27** [comment] 2020-08-13 13:18
I'm on ESET NOD32 AV 13.2.15.0 though I don't think it is preventing Vortex to work.
I recently ran the Win10 latest 2004 build update only to find that it is slowing down alot of my programs and games so I did a system restore to the current build now. Could that be the reason?

**Comment by popsoda27** [comment] 2020-08-13 13:24
Vortex was working fine before I updated Windows, then after the update I didnt get to start Vortex bcos of the performance issues with several of the other programs I have distracting me, causing me to eventually decide to do a system restore. After which I tried to launch Vortex and thus the error.

Maybe the Win10 update did some deep changes that had residual effect even when I restored? Or the restore didn't managed to restore certain stuff maybe.

**Comment by IDCs** [comment] 2020-08-13 13:36
@popsoda27 I guess it's possible something got corrupted in the registry during the restoration/update causing Vortex to look for the native library in the wrong location.. It's going to be hard to reproduce this, but I'll try to update/restore as you have and see if I manage to.

**Comment by IDCs** [comment] 2020-08-14 05:50
Sorry @popsoda27, couldn't reproduce it - I'm afraid that either way there's not much we can do to fix this on our end as registry or OS file corruption can take many forms and makes it pretty much impossible to protect against. One thing you can try is, start up a command prompt with administrator rights and run the "sfc /scannow" command to let Windows try to repair itself.

Going to close this issue as this is guaranteed to be an environment issue and not caused by Vortex itself. Please do reply if you manage to fix it as it could help other users that encounter this in the future.

**Closed by IDCs** 2020-08-14 05:50 UTC
Labels: waiting for reply
