### ISSUE TITLE
odd white static when using vortex on a 1440p monitor

### ISSUE THREAD

**Issue by beastbro9823** [Nexus-Mods/Vortex#11457] opened 2022-03-20 14:36 UTC
**Describe the bug**
at random intervals the launcher has white static/artifacts that last for random amounts of time and varies in intensity. also puts heavy strain on the integrated gpu of my laptop.
it is NOT the blurry issue, as other than the static the graphics are crisp.
this did not happen on my device with a 1080p monitor

**To Reproduce**
1: install vortex on a device using a 1440p monitor
2: noise will pop up seemingly at random

**Expected behavior**
no graphical bugs

**Platform (please complete the following information):**
Windows 10
Vortex Version 1.5.7

**Additional context**
I am on a laptop with an NVidia discrete gpu and an amd cpu with integrated graphics. vortex uses the integrated gpu for its graphics.

Screenshots:

<img width="1280" alt="Screenshot 2022-03-20 100947" src="https://user-images.githubusercontent.com/101981090/159167595-5d289955-70e7-4a6e-af78-db2e54cfea84.png">

<img width="1280" alt="Screenshot 2022-03-20 103528" src="https://user-images.githubusercontent.com/101981090/159167618-7a4afde8-f24d-40c2-961b-0996e27c547e.png">

<img width="1280" alt="Screenshot 2022-03-20 103534" src="https://user-images.githubusercontent.com/101981090/159167625-801b842f-667d-4fc0-aacf-9a7f1a17576b.png">

**Comment by TanninOne** [comment] 2022-03-21 07:35
duplicate of #2428

**Closed by TanninOne** 2022-03-21 07:35 UTC
