### ISSUE TITLE
XCOM 2 expansion trouble

### ISSUE THREAD

**Issue by ArcticSocks** [Nexus-Mods/Vortex#7684] opened 2020-10-13 10:41 UTC
Hello! I downloaded a couple of mods for XCOM 2, but how do I make Vortex boot up the expansion pack (WOTC) instead of the vanilla version? I tried manually choosing the WOTC directory in the XCOM 2 folder, but Vortex just chooses the core folder.

**Comment by IDCs** [comment] 2020-10-13 10:49
Hi @ArcticSocks, I'm afraid that the current Vortex extension only supports the original XCOM 2 game - I don't think any of our team owns WOTC or has any modding experience with it, so it might be better if someone from the community could pick this up.

There is already a game request open for WOTC, so I'm going to close this as a duplicate of #6304

**Closed by IDCs** 2020-10-13 10:49 UTC
