### ISSUE TITLE
Vortex Unable to Import LSX file for Baldurs Gate 3 : TypeError: Cannot read properties of undefined (reading 'id')

### ISSUE THREAD

**Issue by Gyrados15** [Nexus-Mods/Vortex#16106] opened 2024-07-24 06:04 UTC
**Describe the bug**
With Vortex I'm able to Export my Loadorder to a File, however, if I then try to import that very same file or try using the "Import from Game" option it throws a "TypeError: Cannot read properties of undefined (reading 'id')"
**To Reproduce**
1. Go to Load Order
2. Click on 'Import From File/Game'
3. Choose File

**Expected behaviour**
Vortex Should load the Order based on the File, especially since the file is in a format It's exporting

**Full Error**
TypeError: Cannot read properties of undefined (reading 'id')
    at C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar.unpacked\bundledPlugins\game-baldursgate3\loadOrder.js:275:40
    at Array.reduce (<anonymous>)
    at C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar.unpacked\bundledPlugins\game-baldursgate3\loadOrder.js:270:44
    at Generator.next (<anonymous>)
    at fulfilled (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar.unpacked\bundledPlugins\game-baldursgate3\loadOrder.js:28:58)
    at tryCatcher (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:15:14)

**Platform (please complete the following information):**
 - OS: Windows 11
 - Vortex Version 1.11.7 (6/11/2024)

**Additional context**
Exporting to files and even to games always works, but trying to import from any of the provided options (even BG33 Mod Manager one) gives the Same error, I have also tried with an Older LSX file from before the Vortex Update, same error.

**Comment by IDCs** [comment] 2024-07-25 06:23
Hi there @Gyrados15  - I'm unable to reproduce this on my end - can you please attach the .lsx file you're trying to import so I can debug this.

**Comment by Gyrados15** [comment] 2024-07-25 08:07
Sure, See attached lsx, one created on July 24th and one created in March
by an older version of vortex both give me the error when I ry import them.
Kind Regards

Gary Shaw

**Comment by Gyrados15** [comment] 2024-07-25 08:09
[Mod Settings.zip](https://github.com/user-attachments/files/16372678/Mod.Settings.zip)

**Comment by IDCs** [comment] 2024-07-25 12:12
Hey @Gyrados15, just committed a fix for your issue - it appears to be caused by a manually added entry in the .lsx files - i.e. some mod you didn't install using Vortex.

Your July file also contains duplicate entries for some mods which suggests it has been modified externally in some way - that will probably cause some issues in-game.

Fix should be out on Monday, but you can just re-install the external mod using Vortex and it should fix it.

**Comment by Gyrados15** [comment] 2024-07-25 12:39
Awesome, thank you so much!  Is there a way for me to filter/see which are
the duplicates?
Kind Regards

Gary Shaw

**Closed** 2024-07-25 12:41 UTC
Labels: waiting for reply, cant reproduce
