### ISSUE TITLE
Suggestion features - number of mod counter, mods section show file name

### ISSUE THREAD

**Issue by Drachen0** [Nexus-Mods/Vortex#6003] opened 2020-03-08 11:14 UTC
**Is your feature request related to a problem? Please describe.**
 In mods section should have mod counter like in NMM that show total mods, installes mods, active mods and in mods section should have show file name option because I have a problem when import mods from NMM mod that have same mod name but not same file name. It show only one file.

**Describe the solution you'd like**
from above developer should consider for add those features to Votex

**Describe alternatives you've considered**
-

**Additional context**
Sorry for my English. I know my English is poor

**Comment by IDCs** [comment] 2020-03-11 08:18
Hi @Drachen0,

thanks for the suggestion - just wanted to make sure you're aware that you can currently get this information by applying certain filters to the mods table. To get a complete mod count, simply press "ctrl + a" which should select all items. At the bottom right it should say "x items selected". Additionally, you can select to group the mods table by mod status - that will give you a clear view of how many mods are enabled/disabled/uninstalled
![image](https://user-images.githubusercontent.com/8960252/76396037-675f3080-6370-11ea-92bb-7e21bd327824.png)

Additionally, when installing/importing different versions of the same mod - Vortex will group these by design. You should be able to switch between these two via the dropdown button in the version column. Is the dropdown button not available on your end ?

**Comment by IDCs** [comment] 2020-03-18 07:35
Closing as the features that @Drachen0 had proposed are already implemented albeit in a different format.

**Closed by IDCs** 2020-03-18 07:35 UTC
Labels: waiting for reply
