### ISSUE TITLE
Games missing from the games menu(Unable to download extensions)

### ISSUE THREAD

**Issue by ggrgg13** [Nexus-Mods/Vortex#14359] opened 2023-05-25 23:52 UTC
Certain games do not appear on the games menu. I've noticed monster hunter rise and dark souls 3, but there are probably more.
This happened after I upgraded from Windows 10 to Windows 11.
I've tried reinstalling Vortex, didn't solve the issue.
<img width="1280" alt="vortex missing game" src="https://github.com/Nexus-Mods/Vortex/assets/123720145/1b357b85-3a16-4bc6-a456-5f77913f3979">

 - OS: [Windows 11]
 - Vortex Version [e.g. 1.8.3]

**Comment by TanninOne** [comment] 2023-05-30 08:27
@ggrgg13 It seems like you're only seeing the games that Vortex ships with, none of the ones maintained by community members.
This might be caused by network issues, are you getting any error messages about that?
Also, try going to Extensions -> Find more, that should list all the extensions (including games) developed by the community, if my suspicion is right that list is empty.
Your log file will probably contain more information

**Comment by ggrgg13** [comment] 2023-05-31 13:55
Yeah. The extension menu is empty and log showed errors that appears to be network issues. Might be because I'm in China. Going to connect to vpn and try again.

**Comment by ggrgg13** [comment] 2023-05-31 14:04
Still the same error.

Allowing it through firewall didn't work either.

**Comment by ggrgg13** [comment] 2023-07-14 16:55
As far as I can tell, this is an issue related to GitHub access being inconsistent in China. GitHub is not banned in China, but for some reason, the connections is unstable. This seems to be affecting Vortex's ability to download extensions somehow, even while using VPN(at least the VPN I'm using can't solve this issue).

**Comment by ggrgg13** [comment] 2023-09-15 20:07
Came to U.S., problem solved. Can download normally now.

**Comment by ggrgg13** [comment] 2023-09-23 09:22
When I go back to China next year, I'll see if a different VPN solves the issue.

**Comment by HawthorneK456** [comment] 2023-10-03 10:12
Hi,

Thank you for your update and confirmation that the issue has been resolved. I will close this issue for now, please feel free to reopen/log a new issue if you experience these issues again.

**Closed by HawthorneK456** 2023-10-03 10:12 UTC
Labels: waiting for reply
