### ISSUE TITLE
Vortex wont launch.

### ISSUE THREAD

**Issue by Nic0Pic0** [Nexus-Mods/Vortex#5032] opened 2019-07-05 14:41 UTC
If I try to launch Vortex It will just freeze on loading srceen.
Windows 10
Also, Fallout 4 works just fine, but I cant access Vortex.

[crash-main-1562336931764.dmp.log](https://github.com/Nexus-Mods/Vortex/files/3363114/crash-main-1562336931764.dmp.log)

**Comment by IDCs** [comment] 2019-07-08 07:22
duplicate of #3050

**Closed by IDCs** 2019-07-08 07:22 UTC
Labels: duplicate
