### ISSUE TITLE
Vortex will not start - not finding Python or Origin Launcher etc

### ISSUE THREAD

**Issue by bongodoctor** [Nexus-Mods/Vortex#13934] opened 2023-01-30 18:18 UTC
Vortex will not even start here are the last few lines from the vortex.log:

Mon, 30 Jan 2023 18:08:31 GMT - info: outdated extensions numOutdated=0
Mon, 30 Jan 2023 18:08:32 GMT - info: [common-interpreters] python not found not found: python
Mon, 30 Jan 2023 18:08:32 GMT - info: [gamestore-origin] Origin launcher not found error=The system cannot find the file specified.
Mon, 30 Jan 2023 18:08:32 GMT - info: [gamestore-uplay] uplay launcher not found error=The system cannot find the file specified.
Mon, 30 Jan 2023 18:08:32 GMT - warn: couldn't initialize extension name=script-extender-installer, err=window is not defined, stack=ReferenceError: window is not defined
    at Object.<anonymous> (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar.unpacked\bundledPlugins\script-extender-installer\index.js:3:52423)
    at r (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar.unpacked\bundledPlugins\script-extender-installer\index.js:1:124)
    at Object.<anonymous> (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar.unpacked\bundledPlugins\script-extender-installer\index.js:3:28569)
    at r (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar.unpacked\bundledPlugins\script-extender-installer\index.js:1:124)
    at Object.<anonymous> (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar.unpacked\bundledPlugins\script-extender-installer\index.js:3:28120)
    at r (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar.unpacked\bundledPlugins\script-extender-installer\index.js:1:124)
    at Object.<anonymous> (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar.unpacked\bundledPlugins\script-extender-installer\index.js:3:22873)
    at r (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar.unpacked\bundledPlugins\script-extender-installer\index.js:1:124)
    at Object.<anonymous> (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar.unpacked\bundledPlugins\script-extender-installer\index.js:3:11912)
    at r (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar.unpacked\bundledPlugins\script-extender-installer\index.js:1:124)
    at C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar.unpacked\bundledPlugins\script-extender-installer\index.js:1:923
    at Object.<anonymous> (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar.unpacked\bundledPlugins\script-extender-installer\index.js:1:933)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1175:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)

I had been getting a failed backup state not created error (see error report https://github.com/Nexus-Mods/Vortex/issues/13933)- but everything else was working fine. Restarted Vortex and then nothing - not sure if this is an update to Vortex or just a coincidence...

**Comment by bongodoctor** [comment] 2023-01-30 18:28
Looking in: C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar.unpacked\bundledPlugins\common-interpreters Python is indeed missing - only an index.js and an info.json file same with the other two directories mentioned:

C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar.unpacked\bundledPlugins\gamestore-origin

C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar.unpacked\bundledPlugins\gamestore-uplay

Python is installed and running on the PC at C:\Users\bongo\AppData\Local\Microsoft\WindowsApps - so I am not sure what is supposed to be in those folders? Just a link to the full Python.exe? Or do you provide a bundled version in this folder. No idea what would go in the other folders though... As I can't start Vortex I won't be able to install an update (maybe manually?) so might have to reinstall - but very worried I am going to lose all of my settings/profiles and mods etc :(

**Comment by bongodoctor** [comment] 2023-01-30 19:18
Ok after reading some forum posts tried re-installing Vortex leaving all of the mods and profiles etc as is - but got the same result - still won't run and has the same load error... :( So looks like I will have to delete a file somewhere which is causing the issue...

**Comment by bongodoctor** [comment] 2023-01-30 21:18
I have pasted the vortex.log last entry: https://pastebin.com/TzbWrL23

**Comment by TanninOne** [comment] 2023-01-31 09:06
What you posted aren't really issues. Vortex identifies the python installation, if there is one, just in case you set up a tool that requires python as the interpreter. But unless you have python installed and you really need it for one of the tools, this isn't a problem.

Both the Origin and UPlay launcher messages are non-issues, assuming you actually don't have those launchers installed and the "window is not defined" is a bug but not  one that should be causing problems.

The real problem is indeed your state again, the next thing after that last message would be Vortex initially loading the state, so this is effectively a duplicate of #13933

**Closed by TanninOne** 2023-01-31 09:06 UTC
