### ISSUE TITLE
Some tools added in Vortex need to add DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=0 to work properly

### ISSUE THREAD

**Issue by darkrain261** [Nexus-Mods/Vortex#13215] opened 2022-10-01 07:22 UTC
**Describe the bug**
Some tools won't start or work incorrectly if start through Vortex unless you add DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=0 in the environment variable. 
For example: Synthesis won't start. It opens and closes immediately.
DynDOLOD will return E0434352 error when using LODGenx64Win.exe for generating meshes.

**To Reproduce**
For Synthesis
1. Go to 'Vortex' dashboard
2. Click on 'Add tool'
3. Add "Synthesis"
4. Open Synthesis through Vortex
5. See error

For DynDOLOD:
1. Go to 'Vortex' dashboard
2. Click on 'Add tool'
3. Add "DynDOLODx64"
4. Run as normal
5. Error occur when LODGenx64Win generating terrain underside.

**Expected behavior**
Synthesis will open as normal.
DynDOLOD will run without error.

**Platform (please complete the following information):**
 - OS: Windows 10
 - Vortex Version 0.16.13
 - NET runtime 6.0.9

**Additional context**
If I add DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=0 in the environment variable in the shortcuts in Vortex. Then all these tools will work normally.

**Comment by TanninOne** [comment] 2022-10-04 14:21
duplicate of #13200

**Closed by TanninOne** 2022-10-04 14:21 UTC
