### ISSUE TITLE
Infinite switching profile to default screen and loot process died.

### ISSUE THREAD

**Issue by Hellsgaze** [Nexus-Mods/Vortex#13509] opened 2022-11-16 20:34 UTC
Today I opened the Vortex as usual and the folowing notification has apared:

![LOOT Process died](https://user-images.githubusercontent.com/75762406/202287709-22c4f956-d635-4c35-8da9-cabebb6247f9.png)
![LOOT Process died log](https://user-images.githubusercontent.com/75762406/202287731-c2e8791a-ec3c-4d36-8932-7205848310bb.png)

And also, every time I try to manage other game it stucks on the "switching to profile: default" screen.
I used Vortex every day on the past week and didn't change anything, so I have no idea what's going on or how to fix these problems.

![Infinite Swithing Screen](https://user-images.githubusercontent.com/75762406/202288331-4278514b-5907-4c81-b251-d749dec9c169.png)

**Comment by Hellsgaze** [comment] 2022-11-16 20:36
I already tried to reinstall Vortex but it didn't solve any of the problems.

**Comment by melolololo** [comment] 2022-11-16 22:19
Having exactly same problem without a solution, I used it just yesterday and everything works fine until todays update, and then this.
Have you found any solution? 
Thank in advance

**Comment by Hellsgaze** [comment] 2022-11-16 22:34
> 

Not yet. :/

Maybe it's an update bug and they will fix it soon, I hope.

**Comment by melolololo** [comment] 2022-11-17 03:39
Hi Hellsgaze
Not sure if you have this problem fixed yet but I found solution on other post.
https://github.com/Nexus-Mods/Vortex/issues/13505#issuecomment-1316830318
which says " It is fixed for me by disabling the Cyberpunk 2077 extension in Vortex extensions. I'm sorry for my English and I hope this helps you. "
I tried this and its work.
Hope this helps :)

**Comment by TanninOne** [comment] 2022-11-17 08:22
duplicate of #13505

**Closed by TanninOne** 2022-11-17 08:22 UTC
