### ISSUE TITLE
[BUG] (Dragons Dogma) Fails to install mod correctly in certain cases

### ISSUE THREAD

**Issue by BurhanDanger** [Nexus-Mods/Vortex#12626] opened 2022-08-06 10:51 UTC
Context
gamemode = Dragon's Dogma

**Platform:**
 - OS: Windows 10
 - Architecture	x64
 - Vortex Version 1.5.13 (stable)

**Description and way to reproduce:**

Game fails to load when installing a mod ~~in certain way. Other way works fine~~.

Using only 1 Mod. 
Mod in question: [Great Mod Compilation 1.6b_Light version-193-1-6b](https://www.nexusmods.com/dragonsdogma/mods/193)

Two scenarios:

1. [Uninstalled] -> [Enabled] :

Staging folder(Staging\dragonsdogma) -> 

__merged\rom\game_main.arc   [62,768,927 bytes]
Great Mod Compilation 1.6b_Light version-193-1-6b\rom\game_main.arc   [62,478,647 bytes]

(This merged file is replaced in the game directory)

Result: Game bugs out when starting new game with following message.
""Fatal error.""
"Failed to open file.
.../effect/mod/m_cm000_07\m_cn000_07_01.mod 3"

2. [Uninstalled] -> [Unpack(as-is)] -> [Enabled] :

Staging folder(Staging\dragonsdogma) -> 

__merged\nativePC\rom\game_main.arc   [62,478,647 bytes]
Great Mod Compilation 1.6b_Light version-193-1-6b\nativePC\rom\game_main.arc   [62,478,647 bytes]

EDIT2: New nativePC folder created inside nativePC. So it doesn't really replace anything.

Result: ~~Game works perfectly when launching from new game.~~ Game works because mod isn't installed correctly. 

**Additional**

EDIT1: On this note is it possible to disable ARCTool from extracting and then re-archiving the mods?

**Comment by IDCs** [comment] 2023-12-07 05:27
duplicate of https://github.com/Nexus-Mods/Vortex/issues/12820

**Closed by IDCs** 2023-12-07 05:27 UTC
Labels: bug :bug:
