### ISSUE TITLE
Suggestion - Search bar for Manage Rules

### ISSUE THREAD

**Issue by adamstuck** [Nexus-Mods/Vortex#5834] opened 2019-12-29 11:39 UTC
**Is your feature request related to a problem? Please describe.**
I have 250+ mods installed so when I want to make a mod load after another, I have to scroll through this huge unsorted list of rules and try to find the mod I am looking for.

**Describe the solution you'd like**
A search bar at the top of the Manage Rules window. So if I want to change rules for a specific mod I can use the search bar to find it quickly. The search bar should hide all the rules that don't match the mod being searched.

**Comment by TanninOne** [comment] 2020-01-02 11:40
duplicate of #5308

**Closed by TanninOne** 2020-01-02 11:40 UTC
Labels: enhancement
