### ISSUE TITLE
Vortex can't install anything because of nodejs issues

### ISSUE THREAD

**Issue by DerekZiemba** [Nexus-Mods/Vortex#14982] opened 2023-12-08 23:16 UTC
# **Describe the bug**

Vortex doesn't work at all and has never worked.  I tried back in June but couldn't get it to work.  I tried now, still can't get it to work. 

* Cyberpunk 2077 Vortex Support
```
Failed to load: Cannot find module 'bluebird'
Require stack:
- C:\Games\AppData.Roaming\Vortex\plugins\Vortex Extension Update - Cyberpunk 2077 Vortex Support v0.10.1\index.js
- C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\vortex-run\lib\index.js
- C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js
- C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\index.html
```

* Hogwarts Legacy Vortex Extension 
```
Failed to load: Cannot find module 'semver'
Require stack:
- C:\Games\AppData.Roaming\Vortex\plugins\Vortex Extension Update - Hogwarts Legacy Vortex Extension v0.3.5\index.js
- C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\vortex-run\lib\index.js
- C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js
- C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\index.html
```

* Red Dead Redemption 2 Support
```
Failed to load: Cannot find module 'react'
Require stack:
- C:\Games\AppData.Roaming\Vortex\plugins\Vortex Extension Update - Red Dead Redemption 2 Support v0.1.2\index.js
- C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\vortex-run\lib\index.js
- C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js
- C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\index.html
```

* Vortex Extension for Starfield
```
Failed to load: Cannot find module 'turbowalk'
Require stack:
- C:\Games\AppData.Roaming\Vortex\plugins\Vortex Extension Update - Starfield Vortex Extension v0.5.7\index.js
- C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\vortex-run\lib\index.js
- C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js
- C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\index.html
```

**To Reproduce**
1. Freshly Install Vortex
2. Try to do anything with it. 

**Expected behavior**
It to work for anything, anything at all. 

**Screenshots**

**Platform (please complete the following information):**
 - OS: Windows 11 Education 22H2
 - Vortex Version 1.9.10
 - System Specs https://i.imgur.com/QGb4jBb.png

**Additional context**
The primary use of this machine is Software Development.  Some nodejs things that may??? be causing odd behaviors:    
* I use Volta JS Toolchain Manager: https://github.com/volta-cli/volta
* EnvironmentVariables:
   * NODE_PATH = C:\VOLTA_HOME\tools\shared;C:\VOLTA_HOME\tools\image\packages;C:\VOLTA_HOME\bin
      *  C:\VOLTA_HOME is a symlink 
   * VOLTA_HOME = T:\AppData.Local\VOLTA_HOME
      * Because I don't want Gigabytes of node_modules included with my Windows Backups. `node-gyp` & `npm-cache` are also directed to `T:\AppData.Local` 
* Games are installed to `C:\Games`, but that's just a symlink to `T:\Games`.  That goes for anything relatively big that I don't care if I lost, where the `T:\` drive is temporary. This volume is a `MSFT Storage Space` backed by 8 Samsung 870 Evos.

**Comment by GabenGar** [comment] 2023-12-09 18:54
You are bravely using symlinks on windows on top of custom javascript package management tools (which very likely resolve modules in their own quirky ways which may or may not be aware of symlinks). First you'd have to check if vortex's built-in nodejs even runs with privileges to resolve symlinks. But the problem might be related to `.asar` file paths which look like directories, but [`.asar`](https://github.com/electron/asar) are archive files.
You should rev up a barebone Windows 11 VM and see if you encounter the same problem using standard NodeJS and Vortex installation paths within it. This way you can at least tell if the problem is your particular setup or those dependencies.

**Comment by IDCs** [comment] 2023-12-14 07:40
Hi there!

I'm afraid even Vortex itself has some issues with reparse points due to some of the libraries it uses (https://github.com/Nexus-Mods/Vortex/issues/15010). As @GabenGar mentioned, a standard NodeJS and Vortex installation is currently required when developing.

Given that Vortex is being phased out in favor of Nexus.App, it's currently out of scope to replace these libraries to support your type of setup. We will forward this to the App team so they're aware of your specific requirements.

**Closed by IDCs** 2023-12-14 07:40 UTC

**Comment by DerekZiemba** [comment] 2023-12-14 12:37
> a standard NodeJS and Vortex installation is currently required when developing.

Just to clarify, I'm not developing for Vortex, a mod, or a game.  Are you saying everyone who uses Vortex installs NodeJS?  
I'm under the impression it bundled its own NodeJS (versioning nightmare) and that it in no way should interact with a NodeJS external to it.  AFAIK, it properly avoids interacting with any external NodeJS & friends. I tried manually installing the NodeJS & module versions listed in `Vortex --> 3dot menu --> About` globally, but it had no impact. 

----------

Regarding #15010:    
I was gonna mention "Try a MountPoint instead of a Junction/Symlink"...  But only now realized I incorrectly said I was using Junctions/Symlinks. I'm actually using Volume MountPoints.   
_I do this as it adds robustness & simplifies Backup & Restore (dedicate volumes/drives to specific folders). Additionally all paths remain rooted in `C:\` which prevents breaking configs, scripts, & paths between PC's/VM's (different drive letters, etc) with file synchronization/cloud._ 

![image](https://github.com/Nexus-Mods/Vortex/assets/7283693/9fce81bb-8f22-4d1b-b085-b7468854ffb5)

------------

So as it stands:  
 * Vortex has its own embedded NodeJS and none of my NodeJS stuff should effect it. 
 * I'm actually using MountPoints, which AFAIK should avoid typical Symlink/Junction issues.

Only now do I realize the error path `C:\Games\AppData.Roaming\Vortex` contains both a MountPoint & a Junction. Previously I stopped at `C:\Games` (the MountPoint I mistakenly identified as a hardlink/junction) and was blind to the real problem:  `C:\Users\Derek\AppData\Roaming\Vortex` was redirected to `C:\Games\AppData.Roaming\Vortex`.    
It never got cleaned up, leaving a trap for me to stumble into half a year later while attempting to  "fresh" install Vortex. 

After removing that Junction VORTEX WORKS!!! --- Or at least the Extensions installed

**Comment by IDCs** [comment] 2023-12-14 12:53
Oh right! I was under the impression you're trying to set-up a development environment. Regular Vortex installations will definitely not interact with external NodeJS installations.

But yeah junctions will absolutely cause issues. Glad you managed to sort it out :)
