### ISSUE TITLE
Unable to set download directory for Skyrim VR

### ISSUE THREAD

**Issue by nimiwio** [Nexus-Mods/Vortex#131] opened 2018-04-15 16:26 UTC
When downloading mods for Skyrim VR by opening the Nexus link, the files are not downloaded to the directory specified in Settings -> Mods: "Download Path". I suspect this is because the mods are associated with SSE and not SkyrimVR, and the Settings page only allows specifying the settings for games which are installed. However, I am unable to change the download location for SSE since it is not installed.
![skyrimvr_download_directory](https://user-images.githubusercontent.com/5767923/38780660-0ffc25ec-408f-11e8-916b-5c71df6d46bc.png)

**Comment by M4lik** [comment] 2018-04-16 07:26
This is a duplicate of #130.

**Comment by TanninOne** [comment] 2018-04-16 07:42
please track this in #130

**Closed by TanninOne** 2018-04-16 07:42 UTC
