### ISSUE TITLE
Suggestion: Syncing mods

### ISSUE THREAD

**Issue by BlikTomaat** [Nexus-Mods/Vortex#3044] opened 2019-01-30 13:24 UTC
It would be neat to be able to sync your mods through the platform, maybe by logging in to Google Drive or Dropbox and place a text file with all the installed mods (download link synchronisation instead of the mods themselves). This way not much network traffic is needed and the mods would still be downloaded through the nexus mods servers. It may be a long shot but I thought maybe this would be a neat function. Thanks for taking the time looking into this and gl and hf further development :).

**Comment by TanninOne** [comment] 2019-04-24 14:26
duplicate of #2795

**Closed by TanninOne** 2019-04-24 14:26 UTC
Labels: enhancement
