### ISSUE TITLE
Add native linux support

### ISSUE THREAD

**Issue by saltedcoffii** [Nexus-Mods/Vortex#9311] opened 2021-05-16 20:33 UTC
Vortex uses is written in javascript and uses node. Node is inherently cross-platform, so porting to Linux (or other unix-like systems like MacOS) should be easier than if it was written in a compiled language.

Thank you!

**Comment by IDCs** [comment] 2021-05-17 05:27
duplicate of #2862

**Closed by IDCs** 2021-05-17 05:27 UTC
