### ISSUE TITLE
Don't reset the mods directory location on every new game

### ISSUE THREAD

**Issue by Evanito** [Nexus-Mods/Vortex#5487] opened 2019-09-20 08:36 UTC
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I add a new game and can't use hardlinks because Vortex decided to put the mods directory at the default location. I then have to manually retype it to `E:/VortexMods/{game}`
**Describe the solution you'd like**
Have the default directory be changeable or respect where you are staging other mods.

**Describe alternatives you've considered**
Don't do this and continue to make people overwrite the defaults every time, even though it was made with wildcard support.
**Additional context**
n/a

**Comment by TanninOne** [comment] 2019-09-20 10:17
duplicate of #3042

**Closed by TanninOne** 2019-09-20 10:17 UTC
