### ISSUE TITLE
Failed to load master-/userlist

### ISSUE THREAD

**Issue by Vizuo** [Nexus-Mods/Vortex#11096] opened 2022-02-18 14:47 UTC
**Describe the bug**
Error: invalid number of parameters, expected 3
    at l.handleResponse (E:\Vortex\resources\app.asar.unpacked\bundledPlugins\gamebryo-plugin-management\index.js:2:619596)
    at E:\Vortex\resources\app.asar.unpacked\bundledPlugins\gamebryo-plugin-management\index.js:2:618062
    at Array.forEach (<anonymous>)
    at Socket.<anonymous> (E:\Vortex\resources\app.asar.unpacked\bundledPlugins\gamebryo-plugin-management\index.js:2:618045)
    at Socket.emit (node:events:394:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)

**How it happened**
Download Vortex BETA
install a collection for Skyrim SE
Skyrim SE collection I downloaded only for AE
Deleted Collection and all of my mods (roughly 80 mods)
Got these mods:
Add perk points through the console command
Address library for SKSE Plugins (All in One)
Alternate Start - Live another life
Apocalypse 
Deadly Spell Impacts
Electrify
First Person Magic Animation
Frozen, Electrocuted, Combustion
Fulcimentum
Immersive Sounds Compendium
No Force for Illusion Spells
Ordinator
Papyrus Extender SE
RaceMenu- SE ver.
Realistic Skin and hair - Giants
Realistic Skin and hair - Falmer and Hagraven
SkyUI - Flashing Savegame Fix
SkyUI SE
Spell Learning and Discovery SSE
Strange Runes SE

**Expected behavior**
No error popping up

**Screenshots**
![image](https://user-images.githubusercontent.com/99976675/154704760-df67cc66-9572-44a2-9dfe-ba54844dab57.png)
![image](https://user-images.githubusercontent.com/99976675/154704815-55e63152-a59e-4582-9489-4052f874baf4.png)

**Platform (please complete the following information):**
 - OS: Windows 11
 - Vortex Version: Latest BETA Version ( as of 18/02/22 )

**Additional context**
Also removed all of the mods, still popping up so I think its not a mod problem

**Comment by TanninOne** [comment] 2022-02-21 07:49
duplicate of #11114

**Closed by TanninOne** 2022-02-21 07:49 UTC
